/* net/if.h — network interface names.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_NET_IF_H
#define _SLIBC_NET_IF_H

#include <sys/types.h>

#ifdef __cplusplus
extern "C" {
#endif

unsigned int if_nametoindex(const char *ifname);
char *if_indextoname(unsigned int ifindex, char *ifname);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_NET_IF_H */
