/* sys/auxv.h — auxiliary vector.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_AUXV_H
#define _SLIBC_SYS_AUXV_H

#ifdef __cplusplus
extern "C" {
#endif

#define AT_BASE (7)
#define AT_BASE_PLATFORM (24)
#define AT_CLKTCK (17)
#define AT_EGID (14)
#define AT_ENTRY (9)
#define AT_EUID (12)
#define AT_EXECFD (2)
#define AT_EXECFN (31)
#define AT_FLAGS (8)
#define AT_GID (13)
#define AT_HWCAP (16)
#define AT_HWCAP2 (26)
#define AT_IGNORE (1)
#define AT_MINSIGSTKSZ (51)
#define AT_NOTELF (10)
#define AT_NULL (0)
#define AT_PAGESZ (6)
#define AT_PHDR (3)
#define AT_PHENT (4)
#define AT_PHNUM (5)
#define AT_PLATFORM (15)
#define AT_RANDOM (25)
#define AT_SECURE (23)
#define AT_SYSINFO_EHDR (33)
#define AT_UID (11)

unsigned long getauxval(unsigned long type_);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_SYS_AUXV_H */
