/* sys/auxv.h — auxiliary vector.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_AUXV_H
#define _SLIBC_SYS_AUXV_H

#ifdef __cplusplus
extern "C" {
#endif

unsigned long getauxval(unsigned long type_);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_SYS_AUXV_H */
