/* sys/file.h — whole-file advisory locking.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_FILE_H
#define _SLIBC_SYS_FILE_H

#ifdef __cplusplus
extern "C" {
#endif

#define LOCK_EX (2)
#define LOCK_NB (4)
#define LOCK_SH (1)
#define LOCK_UN (8)

int flock(int fd, int operation);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_SYS_FILE_H */
