/* sys/ioctl.h — device control.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_IOCTL_H
#define _SLIBC_SYS_IOCTL_H

#define FIOCLEX (0x5451)
#define FIONBIO (0x5421)
#define FIONCLEX (0x5450)
#define FIONREAD (0x541B)
#define TCGETS (0x5401)
#define TCSETS (0x5402)
#define TCSETSF (0x5404)
#define TCSETSW (0x5403)
#define TIOCGPGRP (0x540F)
#define TIOCGWINSZ (0x5413)
#define TIOCNOTTY (0x5422)
#define TIOCSCTTY (0x540E)
#define TIOCSPGRP (0x5410)
#define TIOCSWINSZ (0x5414)

int ioctl(int fd, unsigned long request, ...);

#endif /* _SLIBC_SYS_IOCTL_H */
