/* sys/ioctl.h — device control.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_IOCTL_H
#define _SLIBC_SYS_IOCTL_H

#ifdef __cplusplus
extern "C" {
#endif

struct winsize {
    unsigned short ws_row;
    unsigned short ws_col;
    unsigned short ws_xpixel;
    unsigned short ws_ypixel;
};

#define FIOCLEX (0x5451)
#define FIONBIO (0x5421)
#define FIONCLEX (0x5450)
#define FIONREAD (0x541B)
#define TCFLSH (0x540B)
#define TCGETA (0x5405)
#define TCGETS (0x5401)
#define TCGETS2 (0x802C542A)
#define TCSBRK (0x5409)
#define TCSBRKP (0x5425)
#define TCSETA (0x5406)
#define TCSETAF (0x5408)
#define TCSETAW (0x5407)
#define TCSETS (0x5402)
#define TCSETS2 (0x402C542B)
#define TCSETSF (0x5404)
#define TCSETSF2 (0x402C542D)
#define TCSETSW (0x5403)
#define TCSETSW2 (0x402C542C)
#define TCXONC (0x540A)
#define TIOCCBRK (0x5428)
#define TIOCCONS (0x541D)
#define TIOCEXCL (0x540C)
#define TIOCGDEV (0x80045432)
#define TIOCGETD (0x5424)
#define TIOCGEXCL (0x80045440)
#define TIOCGICOUNT (0x545D)
#define TIOCGPGRP (0x540F)
#define TIOCGPKT (0x80045438)
#define TIOCGPTLCK (0x80045439)
#define TIOCGPTN (0x80045430)
#define TIOCGPTPEER (0x5441)
#define TIOCGSERIAL (0x541E)
#define TIOCGSID (0x5429)
#define TIOCGSOFTCAR (0x5419)
#define TIOCGWINSZ (0x5413)
#define TIOCINQ (FIONREAD)
#define TIOCLINUX (0x541C)
#define TIOCMBIC (0x5417)
#define TIOCMBIS (0x5416)
#define TIOCMGET (0x5415)
#define TIOCMIWAIT (0x545C)
#define TIOCMSET (0x5418)
#define TIOCM_CAR (0x040)
#define TIOCM_CD (TIOCM_CAR)
#define TIOCM_CTS (0x020)
#define TIOCM_DSR (0x100)
#define TIOCM_DTR (0x002)
#define TIOCM_LE (0x001)
#define TIOCM_RI (TIOCM_RNG)
#define TIOCM_RNG (0x080)
#define TIOCM_RTS (0x004)
#define TIOCM_SR (0x010)
#define TIOCM_ST (0x008)
#define TIOCNOTTY (0x5422)
#define TIOCNXCL (0x540D)
#define TIOCOUTQ (0x5411)
#define TIOCPKT (0x5420)
#define TIOCPKT_DATA (0x00)
#define TIOCPKT_DOSTOP (0x20)
#define TIOCPKT_FLUSHREAD (0x01)
#define TIOCPKT_FLUSHWRITE (0x02)
#define TIOCPKT_NOSTOP (0x10)
#define TIOCPKT_START (0x08)
#define TIOCPKT_STOP (0x04)
#define TIOCSBRK (0x5427)
#define TIOCSCTTY (0x540E)
#define TIOCSETD (0x5423)
#define TIOCSIG (0x40045436)
#define TIOCSPGRP (0x5410)
#define TIOCSPTLCK (0x40045431)
#define TIOCSSERIAL (0x541F)
#define TIOCSSOFTCAR (0x541A)
#define TIOCSTI (0x5412)
#define TIOCSWINSZ (0x5414)
#define TIOCVHANGUP (0x5437)

int ioctl(int fd, unsigned long request, ...);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_SYS_IOCTL_H */
