/* sys/mman.h — memory mapping.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_MMAN_H
#define _SLIBC_SYS_MMAN_H

#include <sys/types.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MADV_DONTNEED (4)
#define MADV_FREE (8)
#define MADV_NORMAL (0)
#define MADV_RANDOM (1)
#define MADV_SEQUENTIAL (2)
#define MADV_WILLNEED (3)
#define MAP_ANON (0x0020)
#define MAP_ANONYMOUS (MAP_ANON)
#define MAP_FAILED (((void *)((void *)~0)))
#define MAP_FIXED (0x0010)
#define MAP_NORESERVE (0x4000)
#define MAP_PRIVATE (0x0002)
#define MAP_SHARED (0x0001)
#define MAP_STACK (0x20000)
#define MS_ASYNC (1)
#define MS_INVALIDATE (2)
#define MS_SYNC (4)
#define PROT_EXEC (4)
#define PROT_NONE (0)
#define PROT_READ (1)
#define PROT_WRITE (2)

void *mmap(void *addr, size_t len, int prot, int flags, int fd, off_t offset);
int munmap(void *addr, size_t len);
int mprotect(void *addr, size_t len, int prot);
int madvise(void *addr, size_t len, int advice);
int msync(void *addr, size_t len, int flags);
int shm_open(const char *name, int oflag, mode_t mode);
int shm_unlink(const char *name);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_SYS_MMAN_H */
