/* sys/param.h — BSD system parameters.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_PARAM_H
#define _SLIBC_SYS_PARAM_H

#include <sys/types.h>
#include <limits.h>

/* Not POSIX, but every Unix C library has it and OpenSSL includes it
 * unconditionally. */
#define MAXPATHLEN PATH_MAX
#define MAXHOSTNAMELEN 64
#define NBBY 8
#ifndef MIN
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a, b) (((a) > (b)) ? (a) : (b))
#endif
#define howmany(x, y) (((x) + ((y) - 1)) / (y))
#define roundup(x, y) ((((x) + ((y) - 1)) / (y)) * (y))
#define powerof2(x) ((((x) - 1) & (x)) == 0)

#endif /* _SLIBC_SYS_PARAM_H */
