/* sys/prctl.h — per-process control.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_PRCTL_H
#define _SLIBC_SYS_PRCTL_H

#ifdef __cplusplus
extern "C" {
#endif

int prctl(int option, ...);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_SYS_PRCTL_H */
