/* sys/random.h — randomness.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_RANDOM_H
#define _SLIBC_SYS_RANDOM_H

#include <sys/types.h>

#ifdef __cplusplus
extern "C" {
#endif

#define GRND_INSECURE (0x0004)
#define GRND_NONBLOCK (0x0001)
#define GRND_RANDOM (0x0002)

ssize_t getrandom(void *buf, size_t buflen, unsigned int flags);
int getentropy(void *buf, size_t len);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_SYS_RANDOM_H */
