/* sys/resource.h — resource limits and usage.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_RESOURCE_H
#define _SLIBC_SYS_RESOURCE_H

#include <sys/types.h>
#include <sys/time.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef unsigned long rlim_t;
struct rlimit {
    rlim_t rlim_cur;
    rlim_t rlim_max;
};
struct rusage {
    struct timeval ru_utime;
    struct timeval ru_stime;
    long ru_maxrss;
    long ru_ixrss;
    long ru_idrss;
    long ru_isrss;
    long ru_minflt;
    long ru_majflt;
    long ru_nswap;
    long ru_inblock;
    long ru_oublock;
    long ru_msgsnd;
    long ru_msgrcv;
    long ru_nsignals;
    long ru_nvcsw;
    long ru_nivcsw;
};

#define PRIO_MAX (20)
#define PRIO_MIN (-20)
#define PRIO_PROCESS (0)
#define RLIMIT_AS (9)
#define RLIMIT_CORE (4)
#define RLIMIT_CPU (0)
#define RLIMIT_DATA (2)
#define RLIMIT_FSIZE (1)
#define RLIMIT_NOFILE (7)
#define RLIMIT_NPROC (6)
#define RLIMIT_STACK (3)
#define RLIM_INFINITY (((rlim_t)~0))

int getrlimit(int resource, struct rlimit *rlim);
int setrlimit(int resource, const struct rlimit *rlim);
int getrusage(int resource, struct rusage *usage);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_SYS_RESOURCE_H */
