/* sys/select.h — synchronous descriptor multiplexing.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_SELECT_H
#define _SLIBC_SYS_SELECT_H

#include <sys/types.h>
#include <sys/time.h>

typedef struct {
    unsigned long fds_bits[16];
} fd_set;

#define FD_SETSIZE (1024)

#define FD_CLR(fd, set) ((void)((set)->fds_bits[(unsigned long)(fd) / (8 * sizeof(unsigned long))] &= ~(1UL << ((unsigned long)(fd) % (8 * sizeof(unsigned long))))))
#define FD_ISSET(fd, set) (((set)->fds_bits[(unsigned long)(fd) / (8 * sizeof(unsigned long))] & (1UL << ((unsigned long)(fd) % (8 * sizeof(unsigned long))))) != 0)
#define FD_SET(fd, set) ((void)((set)->fds_bits[(unsigned long)(fd) / (8 * sizeof(unsigned long))] |= 1UL << ((unsigned long)(fd) % (8 * sizeof(unsigned long)))))
#define FD_ZERO(set) do { \
        unsigned long *__slibc_fds = (set)->fds_bits; \
        unsigned long __slibc_i; \
        for (__slibc_i = 0; \
             __slibc_i < sizeof((set)->fds_bits) / sizeof(unsigned long); \
             __slibc_i++) { \
            __slibc_fds[__slibc_i] = 0; \
        } \
    } while (0)

int select(int nfds, fd_set *readfds, fd_set *writefds, fd_set *errorfds, struct timeval *timeout);

#endif /* _SLIBC_SYS_SELECT_H */
