/* sys/socket.h — sockets.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_SOCKET_H
#define _SLIBC_SYS_SOCKET_H

#include <sys/types.h>
#include <sys/uio.h>

typedef unsigned int socklen_t;
typedef unsigned short sa_family_t;
struct sockaddr {
    sa_family_t sa_family;
    char sa_data[14];
};
struct sockaddr_storage {
    sa_family_t ss_family;
    char __ss_padding[118];
    unsigned long __ss_align;
};
struct msghdr {
    void *msg_name;
    socklen_t msg_namelen;
    struct iovec *msg_iov;
    size_t msg_iovlen;
    void *msg_control;
    size_t msg_controllen;
    int msg_flags;
};
struct cmsghdr {
    size_t cmsg_len;
    int cmsg_level;
    int cmsg_type;
};
struct ucred {
    pid_t pid;
    uid_t uid;
    gid_t gid;
};

#define AF_INET (2)
#define AF_INET6 (10)
#define AF_LOCAL (AF_UNIX)
#define AF_UNIX (1)
#define AF_UNSPEC (0)
#define MSG_CMSG_CLOEXEC (0x40000000)
#define MSG_CTRUNC (8)
#define MSG_DONTROUTE (4)
#define MSG_DONTWAIT (0x40)
#define MSG_EOR (0x80)
#define MSG_NOSIGNAL (0x4000)
#define MSG_OOB (1)
#define MSG_PEEK (2)
#define MSG_TRUNC (0x20)
#define MSG_WAITALL (0x100)
#define PF_INET (AF_INET)
#define PF_INET6 (AF_INET6)
#define PF_LOCAL (AF_LOCAL)
#define PF_UNIX (AF_UNIX)
#define PF_UNSPEC (AF_UNSPEC)
#define SCM_CREDENTIALS (2)
#define SCM_RIGHTS (1)
#define SHUT_RD (0)
#define SHUT_RDWR (2)
#define SHUT_WR (1)
#define SOCK_CLOEXEC (O_CLOEXEC)
#define SOCK_DGRAM (2)
#define SOCK_NONBLOCK (O_NONBLOCK)
#define SOCK_RAW (3)
#define SOCK_SEQPACKET (5)
#define SOCK_STREAM (1)
#define SOL_SOCKET (1)
#define SOMAXCONN (4096)
#define SO_BROADCAST (6)
#define SO_DONTROUTE (5)
#define SO_ERROR (4)
#define SO_KEEPALIVE (9)
#define SO_LINGER (13)
#define SO_PASSCRED (16)
#define SO_PEERCRED (17)
#define SO_RCVBUF (8)
#define SO_RCVTIMEO (20)
#define SO_REUSEADDR (2)
#define SO_REUSEPORT (15)
#define SO_SNDBUF (7)
#define SO_SNDTIMEO (21)
#define SO_TYPE (3)

#define CMSG_FIRSTHDR(mhdr) ((mhdr)->msg_controllen >= sizeof(struct cmsghdr) ? (struct cmsghdr *)(mhdr)->msg_control : (struct cmsghdr *)0)
#define CMSG_NXTHDR(mhdr, cmsg) ((cmsg)->cmsg_len < sizeof(struct cmsghdr) \
     || (cmsg)->cmsg_len > (mhdr)->msg_controllen \
     || CMSG_ALIGN((cmsg)->cmsg_len) < (cmsg)->cmsg_len \
         ? (struct cmsghdr *)0 \
     : ((unsigned char *)(cmsg) + CMSG_ALIGN((cmsg)->cmsg_len) + sizeof(struct cmsghdr) \
                > (unsigned char *)(mhdr)->msg_control + (mhdr)->msg_controllen \
            ? (struct cmsghdr *)0 \
            : (struct cmsghdr *)((unsigned char *)(cmsg) + CMSG_ALIGN((cmsg)->cmsg_len))))
#define CMSG_DATA(cmsg) ((unsigned char *)((struct cmsghdr *)(cmsg) + 1))
#define CMSG_ALIGN(len) (((len) + sizeof(size_t) - 1) & ~(sizeof(size_t) - 1))
#define CMSG_SPACE(len) (CMSG_ALIGN(len) + CMSG_ALIGN(sizeof(struct cmsghdr)))
#define CMSG_LEN(len) (CMSG_ALIGN(sizeof(struct cmsghdr)) + (len))

int socket(int domain, int ty, int protocol);
int socketpair(int domain, int ty, int protocol, int *sv);
int bind(int sockfd, const struct sockaddr *addr, socklen_t addrlen);
int listen(int sockfd, int backlog);
int accept(int sockfd, struct sockaddr *addr, socklen_t *addrlen);
int accept4(int sockfd, struct sockaddr *addr, socklen_t *addrlen, int flags);
int connect(int sockfd, const struct sockaddr *addr, socklen_t addrlen);
int getsockname(int sockfd, struct sockaddr *addr, socklen_t *addrlen);
int getpeername(int sockfd, struct sockaddr *addr, socklen_t *addrlen);
int getsockopt(int sockfd, int level, int name, void *value, socklen_t *option_len);
int setsockopt(int sockfd, int level, int name, const void *value, socklen_t option_len);
ssize_t send(int sockfd, const void *buf, size_t len, int flags);
ssize_t sendto(int sockfd, const void *buf, size_t len, int flags, const struct sockaddr *addr, socklen_t addrlen);
ssize_t sendmsg(int sockfd, const struct msghdr *msg, int flags);
ssize_t recv(int sockfd, void *buf, size_t len, int flags);
ssize_t recvfrom(int sockfd, void *buf, size_t len, int flags, struct sockaddr *addr, socklen_t *addrlen);
ssize_t recvmsg(int sockfd, struct msghdr *msg, int flags);
int shutdown(int sockfd, int how);

#endif /* _SLIBC_SYS_SOCKET_H */
