/* sys/stat.h — file status.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_STAT_H
#define _SLIBC_SYS_STAT_H

#include <sys/types.h>
#include <time.h>

#ifdef __cplusplus
extern "C" {
#endif

struct stat {
    dev_t st_dev;
    ino_t st_ino;
    nlink_t st_nlink;
    mode_t st_mode;
    uid_t st_uid;
    gid_t st_gid;
    int __pad0;
    dev_t st_rdev;
    off_t st_size;
    blksize_t st_blksize;
    blkcnt_t st_blocks;
    time_t st_atime;
    long st_atime_nsec;
    time_t st_mtime;
    long st_mtime_nsec;
    time_t st_ctime;
    long st_ctime_nsec;
    long __unused[3];
};
struct stat64 {
    dev_t st_dev;
    ino_t st_ino;
    nlink_t st_nlink;
    mode_t st_mode;
    uid_t st_uid;
    gid_t st_gid;
    int __pad0;
    dev_t st_rdev;
    off_t st_size;
    blksize_t st_blksize;
    blkcnt_t st_blocks;
    time_t st_atime;
    long st_atime_nsec;
    time_t st_mtime;
    long st_mtime_nsec;
    time_t st_ctime;
    long st_ctime_nsec;
    long __unused[3];
};

#define S_IFBLK (0060000)
#define S_IFCHR (0020000)
#define S_IFDIR (0040000)
#define S_IFIFO (0010000)
#define S_IFLNK (0120000)
#define S_IFMT (0170000)
#define S_IFREG (0100000)
#define S_IFSOCK (0140000)
#define S_IRGRP (0040)
#define S_IROTH (0004)
#define S_IRUSR (0400)
#define S_IRWXG (0070)
#define S_IRWXO (0007)
#define S_IRWXU (0700)
#define S_IWGRP (0020)
#define S_IWOTH (0002)
#define S_IWUSR (0200)
#define S_IXGRP (0010)
#define S_IXOTH (0001)
#define S_IXUSR (0100)
#define UTIME_NOW (0x3fffffff)
#define UTIME_OMIT (0x3ffffffe)
#define S_ISBLK(mode) (((mode) & S_IFMT) == S_IFBLK)
#define S_ISCHR(mode) (((mode) & S_IFMT) == S_IFCHR)
#define S_ISDIR(mode) (((mode) & S_IFMT) == S_IFDIR)
#define S_ISIFO(mode) (((mode) & S_IFMT) == S_IFIFO)
#define S_ISLNK(mode) (((mode) & S_IFMT) == S_IFLNK)
#define S_ISREG(mode) (((mode) & S_IFMT) == S_IFREG)
#define S_ISSOCK(mode) (((mode) & S_IFMT) == S_IFSOCK)

int stat(const char *path, struct stat *buf);
int lstat(const char *path, struct stat *buf);
int fstat(int fd, struct stat *buf);
int fstatat(int dirfd, const char *path, struct stat *buf, int flags);
int chmod(const char *path, mode_t mode);
int fchmod(int fd, mode_t mode);
int fchmodat(int dirfd, const char *path, mode_t mode, int flags);
mode_t umask(mode_t mask);
int mkdir(const char *path, mode_t mode);
int mkdirat(int dirfd, const char *path, mode_t mode);
int mkfifo(const char *path, mode_t mode);
int mknod(const char *path, mode_t mode, dev_t dev);
int utimensat(int dirfd, const char *path, const struct timespec *times, int flags);
int futimens(int fd, const struct timespec *times);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_SYS_STAT_H */
