/* sys/statfs.h — file-system statistics, Linux flavour.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_STATFS_H
#define _SLIBC_SYS_STATFS_H

#include <sys/types.h>

typedef struct {
    int __val[2];
} fsid_t;
struct statfs {
    fsword_t f_type;
    fsword_t f_bsize;
    fsblkcnt_t f_blocks;
    fsblkcnt_t f_bfree;
    fsblkcnt_t f_bavail;
    fsfilcnt_t f_files;
    fsfilcnt_t f_ffree;
    fsid_t f_fsid;
    fsword_t f_namelen;
    fsword_t f_frsize;
    fsword_t f_flags;
    fsword_t f_spare[4];
};

int statfs(const char *path, struct statfs *buf);
int fstatfs(int fd, struct statfs *buf);

#endif /* _SLIBC_SYS_STATFS_H */
