/* sys/syscall.h — system-call numbers.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_SYSCALL_H
#define _SLIBC_SYS_SYSCALL_H

#define FUTEX_BITSET_MATCH_ANY (-1)
#define FUTEX_CLOCK_REALTIME (256)
#define FUTEX_CMP_REQUEUE (4)
#define FUTEX_PRIVATE_FLAG (128)
#define FUTEX_REQUEUE (3)
#define FUTEX_WAIT (0)
#define FUTEX_WAIT_BITSET (9)
#define FUTEX_WAKE (1)
#define FUTEX_WAKE_BITSET (10)
#define SYS_futex (202)
#define SYS_getrandom (318)
#define SYS_gettid (186)

#endif /* _SLIBC_SYS_SYSCALL_H */
