/* sys/time.h — microsecond-resolution time.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_TIME_H
#define _SLIBC_SYS_TIME_H

#include <sys/types.h>
#include <time.h>
#include <sys/select.h>

#ifdef __cplusplus
extern "C" {
#endif

struct itimerval {
    struct timeval it_interval;
    struct timeval it_value;
};

#define ITIMER_REAL (0)
#define ITIMER_VIRTUAL (1)
#define ITIMER_PROF (2)

int gettimeofday(struct timeval *tp, void *tz);
int lutimes(const char *path, const struct timeval *times);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_SYS_TIME_H */
