/* sys/types.h — POSIX scalar types.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_TYPES_H
#define _SLIBC_SYS_TYPES_H

#ifndef __slibc_noreturn
#  if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#    define __slibc_noreturn _Noreturn
#  elif defined(__GNUC__)
#    define __slibc_noreturn __attribute__((__noreturn__))
#  else
#    define __slibc_noreturn
#  endif
#endif

#ifndef __slibc_aligned
#  if defined(__GNUC__)
#    define __slibc_aligned(n) __attribute__((__aligned__(n)))
#  else
#    define __slibc_aligned(n)
#  endif
#endif

/* `NULL` belongs to the compiler's <stddef.h>, which SlopOS has no C compiler
 * to provide yet (Workstream 1.3). Defined here, guarded, so a hosted
 * compiler's own definition still wins.
 */
#ifndef NULL
#  define NULL ((void *)0)
#endif

typedef unsigned long size_t;
typedef long ssize_t;
typedef int wchar_t;
typedef long off_t;
typedef long off64_t;
typedef long blkcnt_t;
typedef long blksize_t;
typedef long clock_t;
typedef int clockid_t;
typedef unsigned long dev_t;
typedef unsigned long fsblkcnt_t;
typedef unsigned long fsfilcnt_t;
typedef long fsword_t;
typedef unsigned long ino_t;
typedef unsigned int mode_t;
typedef unsigned long nlink_t;
typedef int pid_t;
typedef unsigned int uid_t;
typedef unsigned int gid_t;
typedef unsigned int id_t;
typedef int key_t;
typedef long suseconds_t;
typedef long time_t;
typedef unsigned int useconds_t;
typedef unsigned long pthread_t;
typedef unsigned int pthread_key_t;

#define major(dev) ((unsigned int)((((dev_t)(dev) >> 32) & 0xfffff000) | (((dev_t)(dev) >> 8) & 0x00000fff)))
#define minor(dev) ((unsigned int)((((dev_t)(dev) >> 12) & 0xffffff00) | ((dev_t)(dev) & 0x000000ff)))
#define makedev(major, minor) ((dev_t)((((dev_t)(major) & 0x00000fff) << 8) | (((dev_t)(major) & 0xfffff000) << 32) | ((dev_t)(minor) & 0x000000ff) | (((dev_t)(minor) & 0xffffff00) << 12)))

#endif /* _SLIBC_SYS_TYPES_H */
