/* sys/wait.h — process termination status.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYS_WAIT_H
#define _SLIBC_SYS_WAIT_H

#include <sys/types.h>
#include <sys/resource.h>

#ifdef __cplusplus
extern "C" {
#endif

#define WCONTINUED (8)
#define WNOHANG (1)
#define WUNTRACED (2)

#define WIFEXITED(status) (((status) & 0x7f) == 0)
#define WEXITSTATUS(status) (((status) >> 8) & 0xff)
#define WTERMSIG(status) ((status) & 0x7f)
#define WIFSIGNALED(status) ((signed char)((((status) & 0x7f) + 1)) >= 2)
#define WIFSTOPPED(status) (((status) & 0xff) == 0x7f)
#define WSTOPSIG(status) (((status) >> 8) & 0xff)
#define WIFCONTINUED(status) ((status) == 0xffff)
#define WCOREDUMP(status) (((status) & 0x80) != 0)
#define W_EXITCODE(ret, sig) (((ret) << 8) | (sig))
#define W_STOPCODE(sig) (((sig) << 8) | 0x7f)

pid_t waitpid(pid_t pid, int *status, int options);
pid_t wait(int *status);
pid_t wait4(pid_t pid, int *status, int options, struct rusage *rusage);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_SYS_WAIT_H */
