[package]
name = "slopos-boot"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

test = false
doctest = false

[features]
default = []
tests = ["slopos-testing/tests", "test-hooks", "slopos-ostd/test-helpers"]
test-hooks = ["slopos-core/test-hooks", "slopos-mm/test-hooks", "slopos-drivers/test-hooks"]

[dependencies]
limine = { workspace = true }
slopos-abi = { workspace = true }
slopos-acpi = { workspace = true }
slopos-arch = { workspace = true }
slopos-boot-core = { workspace = true }
slopos-core = { workspace = true }
slopos-cpufreq-core = { workspace = true }
slopos-kernel-services = { workspace = true }
slopos-testing = { workspace = true }
slopos-drivers = { workspace = true }
slopos-fs = { workspace = true }
slopos-mm = { workspace = true }
slopos-net = { workspace = true }
slopos-ostd = { workspace = true }
slopos-sched = { workspace = true }
slopos-video = { workspace = true }
slopos-hermetic = { workspace = true }
