/* assert.h — the diagnostic macro.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_ASSERT_H
#define _SLIBC_ASSERT_H

#include <sys/types.h>

#ifdef __cplusplus
extern "C" {
#endif

__slibc_noreturn void __slibc_assert_fail(const char *expr, const char *file, unsigned int line, const char *func);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_ASSERT_H */

#undef assert
#ifdef NDEBUG
#  define assert(e) ((void)0)
#else
#  define assert(e) \
      ((e) ? (void)0 : __slibc_assert_fail(#e, __FILE__, __LINE__, __func__))
#endif
