/* ctype.h — character classification, in the C locale.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_CTYPE_H
#define _SLIBC_CTYPE_H

#include <locale.h>

#ifdef __cplusplus
extern "C" {
#endif

int isalnum(int c);
int isalpha(int c);
int isblank(int c);
int iscntrl(int c);
int isdigit(int c);
int isgraph(int c);
int islower(int c);
int isprint(int c);
int ispunct(int c);
int isspace(int c);
int isupper(int c);
int isxdigit(int c);
int tolower(int c);
int toupper(int c);
int isascii(int c);
int toascii(int c);
int isalnum_l(int c, locale_t loc);
int isalpha_l(int c, locale_t loc);
int isblank_l(int c, locale_t loc);
int iscntrl_l(int c, locale_t loc);
int isdigit_l(int c, locale_t loc);
int isgraph_l(int c, locale_t loc);
int islower_l(int c, locale_t loc);
int isprint_l(int c, locale_t loc);
int ispunct_l(int c, locale_t loc);
int isspace_l(int c, locale_t loc);
int isupper_l(int c, locale_t loc);
int isxdigit_l(int c, locale_t loc);
int tolower_l(int c, locale_t loc);
int toupper_l(int c, locale_t loc);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_CTYPE_H */
