/* dlfcn.h — dynamic loading; SlopOS is static, so the types exist and the calls do not.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_DLFCN_H
#define _SLIBC_DLFCN_H

typedef struct {
    const char *dli_fname;
    void *dli_fbase;
    const char *dli_sname;
    void *dli_saddr;
} Dl_info;

#define RTLD_GLOBAL (0x100)
#define RTLD_LAZY (1)
#define RTLD_LOCAL (0)
#define RTLD_NOW (2)

#endif /* _SLIBC_DLFCN_H */
