/* errno.h — error numbers.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_ERRNO_H
#define _SLIBC_ERRNO_H

#define errno (*__errno_location())

#ifdef __cplusplus
extern "C" {
#endif

#define E2BIG (7)
#define EACCES (13)
#define EADDRINUSE (98)
#define EADDRNOTAVAIL (99)
#define EAFNOSUPPORT (97)
#define EAGAIN (11)
#define EALREADY (114)
#define EBADF (9)
#define EBADMSG (74)
#define EBUSY (16)
#define ECANCELED (125)
#define ECHILD (10)
#define ECONNABORTED (103)
#define ECONNREFUSED (111)
#define ECONNRESET (104)
#define EDEADLK (35)
#define EDEADLOCK (EDEADLK)
#define EDESTADDRREQ (89)
#define EDOM (33)
#define EDQUOT (122)
#define EEXIST (17)
#define EFAULT (14)
#define EFBIG (27)
#define EHOSTDOWN (112)
#define EHOSTUNREACH (113)
#define EIDRM (43)
#define EILSEQ (84)
#define EINPROGRESS (115)
#define EINTR (4)
#define EINVAL (22)
#define EIO (5)
#define EISCONN (106)
#define EISDIR (21)
#define ELOOP (40)
#define EMFILE (24)
#define EMLINK (31)
#define EMSGSIZE (90)
#define EMULTIHOP (72)
#define ENAMETOOLONG (36)
#define ENETDOWN (100)
#define ENETRESET (102)
#define ENETUNREACH (101)
#define ENFILE (23)
#define ENOBUFS (105)
#define ENODATA (61)
#define ENODEV (19)
#define ENOENT (2)
#define ENOEXEC (8)
#define ENOLCK (37)
#define ENOLINK (67)
#define ENOMEM (12)
#define ENOMSG (42)
#define ENOPROTOOPT (92)
#define ENOSPC (28)
#define ENOSR (63)
#define ENOSTR (60)
#define ENOSYS (38)
#define ENOTBLK (15)
#define ENOTCONN (107)
#define ENOTDIR (20)
#define ENOTEMPTY (39)
#define ENOTRECOVERABLE (131)
#define ENOTSOCK (88)
#define ENOTSUP (EOPNOTSUPP)
#define ENOTTY (25)
#define ENXIO (6)
#define EOPNOTSUPP (95)
#define EOVERFLOW (75)
#define EOWNERDEAD (130)
#define EPERM (1)
#define EPFNOSUPPORT (96)
#define EPIPE (32)
#define EPROTO (71)
#define EPROTONOSUPPORT (93)
#define EPROTOTYPE (91)
#define ERANGE (34)
#define EREMOTE (66)
#define EROFS (30)
#define ESHUTDOWN (108)
#define ESOCKTNOSUPPORT (94)
#define ESPIPE (29)
#define ESRCH (3)
#define ESTALE (116)
#define ETIME (62)
#define ETIMEDOUT (110)
#define ETOOMANYREFS (109)
#define ETXTBSY (26)
#define EUSERS (87)
#define EWOULDBLOCK (EAGAIN)
#define EXDEV (18)

int *__errno_location(void);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_ERRNO_H */
