/* getopt.h — command-line option parsing, with GNU long options.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_GETOPT_H
#define _SLIBC_GETOPT_H

#include <unistd.h>

#ifdef __cplusplus
extern "C" {
#endif

struct option {
    const char *name;
    int has_arg;
    int *flag;
    int val;
};

#define no_argument (0)
#define required_argument (1)
#define optional_argument (2)

int getopt_long(int argc, char *const *argv, const char *optstring, const struct option *longopts, int *longindex);
int getopt_long_only(int argc, char *const *argv, const char *optstring, const struct option *longopts, int *longindex);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_GETOPT_H */
