/* limits.h — implementation limits.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_LIMITS_H
#define _SLIBC_LIMITS_H

#if defined(__has_include_next)
#  if __has_include_next(<limits.h>)
#    include_next <limits.h>
#  endif
#endif

#ifndef CHAR_BIT
#  define CHAR_BIT 8
#  define SCHAR_MIN (-128)
#  define SCHAR_MAX 127
#  define UCHAR_MAX 255
#  ifdef __CHAR_UNSIGNED__
#    define CHAR_MIN 0
#    define CHAR_MAX 255
#  else
#    define CHAR_MIN (-128)
#    define CHAR_MAX 127
#  endif
#  define SHRT_MIN (-32768)
#  define SHRT_MAX 32767
#  define USHRT_MAX 65535
#  define INT_MIN (-2147483647 - 1)
#  define INT_MAX 2147483647
#  define UINT_MAX 4294967295U
#  define LONG_MIN (-9223372036854775807L - 1)
#  define LONG_MAX 9223372036854775807L
#  define ULONG_MAX 18446744073709551615UL
#  define LLONG_MIN (-9223372036854775807LL - 1)
#  define LLONG_MAX 9223372036854775807LL
#  define ULLONG_MAX 18446744073709551615ULL
#endif

#undef MB_LEN_MAX
#define MB_LEN_MAX 4

#define _POSIX_ARG_MAX (4096)
#define HOST_NAME_MAX (64)
#define IOV_MAX (1024)
#define NAME_MAX (255)
#define PATH_MAX (4096)
#define PTHREAD_STACK_MIN (16384)
#define SSIZE_MAX (0x7fffffffffffffff)

#endif /* _SLIBC_LIMITS_H */
