/* locale.h — locale categories.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_LOCALE_H
#define _SLIBC_LOCALE_H

#include <stddef.h>

#define LC_GLOBAL_LOCALE ((locale_t)-1)

#ifdef __cplusplus
extern "C" {
#endif

typedef int nl_item;
struct lconv {
    char *decimal_point;
    char *thousands_sep;
    char *grouping;
    char *int_curr_symbol;
    char *currency_symbol;
    char *mon_decimal_point;
    char *mon_thousands_sep;
    char *mon_grouping;
    char *positive_sign;
    char *negative_sign;
    char int_frac_digits;
    char frac_digits;
    char p_cs_precedes;
    char p_sep_by_space;
    char n_cs_precedes;
    char n_sep_by_space;
    char p_sign_posn;
    char n_sign_posn;
    char int_p_cs_precedes;
    char int_p_sep_by_space;
    char int_n_cs_precedes;
    char int_n_sep_by_space;
    char int_p_sign_posn;
    char int_n_sign_posn;
};
typedef struct _slibc___locale_struct __locale_struct;
typedef __locale_struct *locale_t;

#define LC_CTYPE (0)
#define LC_NUMERIC (1)
#define LC_TIME (2)
#define LC_COLLATE (3)
#define LC_MONETARY (4)
#define LC_MESSAGES (5)
#define LC_ALL (6)
#define LC_CTYPE_MASK (1)
#define LC_NUMERIC_MASK (2)
#define LC_TIME_MASK (4)
#define LC_COLLATE_MASK (8)
#define LC_MONETARY_MASK (16)
#define LC_MESSAGES_MASK (32)
#define LC_ALL_MASK (63)

char *setlocale(int category, const char *locale);
struct lconv *localeconv(void);
struct lconv *localeconv_l(locale_t loc);
locale_t newlocale(int mask, const char *name, locale_t base);
locale_t duplocale(locale_t base);
void freelocale(locale_t loc);
locale_t uselocale(locale_t loc);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_LOCALE_H */
