/* memory.h — the pre-standard home of the memory functions `<string.h>` declares.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_MEMORY_H
#define _SLIBC_MEMORY_H

#include <string.h>

#endif /* _SLIBC_MEMORY_H */
