/* netdb.h — name resolution.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_NETDB_H
#define _SLIBC_NETDB_H

#include <sys/socket.h>
#include <netinet/in.h>

#define h_errno (*__h_errno_location())

#ifdef __cplusplus
extern "C" {
#endif

struct addrinfo {
    int ai_flags;
    int ai_family;
    int ai_socktype;
    int ai_protocol;
    socklen_t ai_addrlen;
    struct sockaddr *ai_addr;
    char *ai_canonname;
    struct addrinfo *ai_next;
};
struct hostent {
    char *h_name;
    char **h_aliases;
    int h_addrtype;
    int h_length;
    char **h_addr_list;
};
struct servent {
    char *s_name;
    char **s_aliases;
    int s_port;
    char *s_proto;
};

#define NI_NUMERICHOST (0x01)
#define NI_NUMERICSERV (0x02)
#define NI_NOFQDN (0x04)
#define NI_NAMEREQD (0x08)
#define NI_DGRAM (0x10)
#define NI_NUMERICSCOPE (0x100)
#define HOST_NOT_FOUND (1)
#define TRY_AGAIN (2)
#define NO_RECOVERY (3)
#define NO_DATA (4)
#define AI_ADDRCONFIG (0x0020)
#define AI_ALL (0x0010)
#define AI_CANONNAME (0x0002)
#define AI_NUMERICHOST (0x0004)
#define AI_NUMERICSERV (0x0400)
#define AI_PASSIVE (0x0001)
#define AI_V4MAPPED (0x0008)
#define EAI_AGAIN (-3)
#define EAI_BADFLAGS (-1)
#define EAI_FAIL (-4)
#define EAI_FAMILY (-6)
#define EAI_MEMORY (-10)
#define EAI_NONAME (-2)
#define EAI_OVERFLOW (-12)
#define EAI_SERVICE (-8)
#define EAI_SOCKTYPE (-7)
#define EAI_SYSTEM (-11)
#define NI_MAXHOST (1025)
#define NI_MAXSERV (32)

int getaddrinfo(const char *node, const char *service, const struct addrinfo *hints, struct addrinfo **res);
void freeaddrinfo(struct addrinfo *res);
const char *gai_strerror(int errcode);
int getnameinfo(const struct sockaddr *sa, socklen_t salen, char *host, socklen_t hostlen, char *serv, socklen_t servlen, int flags);
struct hostent *gethostbyname(const char *name);
struct servent *getservbyname(const char *name, const char *proto);
int *__h_errno_location(void);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_NETDB_H */
