/* nl_types.h — message catalogs.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_NL_TYPES_H
#define _SLIBC_NL_TYPES_H

#include <locale.h>

typedef void *nl_catd;

#ifdef __cplusplus
extern "C" {
#endif

#define NL_SETD (1)
#define NL_CAT_LOCALE (1)

void *catopen(const char *name, int flag);
char *catgets(void *catd, int set, int number, const char *message);
int catclose(void *catd);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_NL_TYPES_H */
