/* poll.h — descriptor polling.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_POLL_H
#define _SLIBC_POLL_H

#include <sys/types.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef unsigned long nfds_t;
struct pollfd {
    int fd;
    short events;
    short revents;
};

#define POLLERR (0x008)
#define POLLHUP (0x010)
#define POLLIN (0x001)
#define POLLNVAL (0x020)
#define POLLOUT (0x004)
#define POLLPRI (0x002)
#define POLLRDNORM (0x040)
#define POLLWRNORM (0x100)

int poll(struct pollfd *fds, nfds_t nfds, int timeout);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_POLL_H */
