/* pthread.h — threads.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_PTHREAD_H
#define _SLIBC_PTHREAD_H

#include <sys/types.h>
#include <time.h>
#include <sched.h>
#include <signal.h>

typedef struct {
    unsigned long __size[7];
} pthread_attr_t;
typedef struct {
    unsigned long __size[5];
} pthread_mutex_t;
typedef struct {
    unsigned int __size[1];
} pthread_mutexattr_t;
typedef struct {
    unsigned long __size[6];
} pthread_cond_t;
typedef struct {
    unsigned int __size[1];
} pthread_condattr_t;
typedef struct {
    unsigned long __size[7];
} pthread_rwlock_t;
typedef struct {
    unsigned long __size[1];
} pthread_rwlockattr_t;

#define PTHREAD_COND_INITIALIZER { { 0 } }
#define PTHREAD_MUTEX_DEFAULT (PTHREAD_MUTEX_NORMAL)
#define PTHREAD_MUTEX_ERRORCHECK (2)
#define PTHREAD_MUTEX_INITIALIZER { { 0 } }
#define PTHREAD_MUTEX_NORMAL (0)
#define PTHREAD_MUTEX_RECURSIVE (1)
#define PTHREAD_RWLOCK_INITIALIZER { { 0 } }

int pthread_create(pthread_t *native, const pthread_attr_t *attr, void * (*f)(void *), void *value);
int pthread_join(pthread_t native, void **value);
int pthread_detach(pthread_t thread);
pthread_t pthread_self(void);
__slibc_noreturn void pthread_exit(void *value);
int pthread_kill(pthread_t thread, int sig);
int pthread_sigmask(int how, const sigset_t *set, sigset_t *oldset);
int pthread_attr_init(pthread_attr_t *attr);
int pthread_attr_destroy(pthread_attr_t *attr);
int pthread_attr_setstacksize(pthread_attr_t *attr, size_t stack_size);
int pthread_attr_getstacksize(const pthread_attr_t *attr, size_t *stack_size);
int pthread_attr_getstack(const pthread_attr_t *attr, void **stackaddr, size_t *stacksize);
int pthread_attr_getguardsize(const pthread_attr_t *attr, size_t *guardsize);
int pthread_attr_setguardsize(pthread_attr_t *attr, size_t guardsize);
int pthread_getattr_np(pthread_t native, pthread_attr_t *attr);
int pthread_setname_np(pthread_t thread, const char *name);
int pthread_getname_np(pthread_t thread, char *name, size_t len);
int pthread_key_create(pthread_key_t *key, void (*dtor)(void *));
int pthread_key_delete(pthread_key_t key);
void *pthread_getspecific(pthread_key_t key);
int pthread_setspecific(pthread_key_t key, const void *value);
int pthread_mutex_init(pthread_mutex_t *lock, const pthread_mutexattr_t *attr);
int pthread_mutex_destroy(pthread_mutex_t *lock);
int pthread_mutex_lock(pthread_mutex_t *lock);
int pthread_mutex_trylock(pthread_mutex_t *lock);
int pthread_mutex_unlock(pthread_mutex_t *lock);
int pthread_mutexattr_init(pthread_mutexattr_t *attr);
int pthread_mutexattr_destroy(pthread_mutexattr_t *attr);
int pthread_mutexattr_settype(pthread_mutexattr_t *attr, int ty);
int pthread_cond_init(pthread_cond_t *cond, const pthread_condattr_t *attr);
int pthread_cond_destroy(pthread_cond_t *cond);
int pthread_cond_wait(pthread_cond_t *cond, pthread_mutex_t *lock);
int pthread_cond_timedwait(pthread_cond_t *cond, pthread_mutex_t *lock, const struct timespec *abstime);
int pthread_cond_signal(pthread_cond_t *cond);
int pthread_cond_broadcast(pthread_cond_t *cond);
int pthread_condattr_init(pthread_condattr_t *attr);
int pthread_condattr_destroy(pthread_condattr_t *attr);
int pthread_condattr_setclock(pthread_condattr_t *attr, clockid_t clock_id);
int pthread_rwlock_init(pthread_rwlock_t *lock, const pthread_rwlockattr_t *attr);
int pthread_rwlock_destroy(pthread_rwlock_t *lock);
int pthread_rwlock_rdlock(pthread_rwlock_t *lock);
int pthread_rwlock_tryrdlock(pthread_rwlock_t *lock);
int pthread_rwlock_wrlock(pthread_rwlock_t *lock);
int pthread_rwlock_trywrlock(pthread_rwlock_t *lock);
int pthread_rwlock_unlock(pthread_rwlock_t *lock);
int pthread_rwlockattr_init(pthread_rwlockattr_t *attr);
int pthread_rwlockattr_destroy(pthread_rwlockattr_t *attr);
int pthread_equal(pthread_t t1, pthread_t t2);
int pthread_attr_getdetachstate(const pthread_attr_t *attr, int *detachstate);
int pthread_attr_setdetachstate(pthread_attr_t *attr, int detachstate);

#endif /* _SLIBC_PTHREAD_H */
