/* resolv.h — DNS resolver.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_RESOLV_H
#define _SLIBC_RESOLV_H

#include <sys/types.h>
#include <netinet/in.h>
#include <arpa/nameser.h>

#ifdef __cplusplus
extern "C" {
#endif

struct __res_state {
    int retrans;
    int retry;
    unsigned long options;
    int nscount;
    struct sockaddr_in nsaddr_list[3];
};

#define MAXNS (3)
#define RES_INIT (0x1)
#define RES_RECURSE (0x40)
#define RES_DEFAULT (0x40)

extern struct __res_state _res;

int res_init(void);
int res_query(const char *dname, int rclass, int rtype, unsigned char *answer, int anslen);
int dn_expand(const unsigned char *msg, const unsigned char *eom, const unsigned char *src, char *dst, int dstsiz);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_RESOLV_H */
