/* sched.h — scheduling.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SCHED_H
#define _SLIBC_SCHED_H

#include <sys/types.h>

#ifdef __cplusplus
extern "C" {
#endif

struct sched_param {
    int sched_priority;
};

int sched_yield(void);
int sched_getaffinity(pid_t pid, size_t cpusetsize, void *cpuset);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_SCHED_H */
