/* sched.h — scheduling.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SCHED_H
#define _SLIBC_SCHED_H

#include <sys/types.h>

#ifdef __cplusplus
extern "C" {
#endif

struct sched_param {
    int sched_priority;
};

#define SCHED_OTHER (0)
#define SCHED_FIFO (1)
#define SCHED_RR (2)

int sched_yield(void);
int sched_getaffinity(pid_t pid, size_t cpusetsize, void *cpuset);
int sched_get_priority_min(int policy);
int sched_get_priority_max(int policy);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_SCHED_H */
