/* semaphore.h — unnamed semaphores.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SEMAPHORE_H
#define _SLIBC_SEMAPHORE_H

#include <sys/types.h>

typedef struct {
    unsigned long __size[4];
} sem_t;

#endif /* _SLIBC_SEMAPHORE_H */
