/* setjmp.h — non-local jumps.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SETJMP_H
#define _SLIBC_SETJMP_H

#include <sys/types.h>

#define setjmp setjmp

#ifdef __cplusplus
extern "C" {
#endif

struct __jmp_buf_tag {
    unsigned long __jmpbuf[8];
    unsigned long __mask_was_saved;
    unsigned long __saved_mask[16];
};
typedef struct __jmp_buf_tag jmp_buf[1];
typedef struct __jmp_buf_tag sigjmp_buf[1];

int setjmp(struct __jmp_buf_tag *env);
int _setjmp(struct __jmp_buf_tag *env);
__slibc_noreturn void longjmp(struct __jmp_buf_tag *env, int val);
__slibc_noreturn void _longjmp(struct __jmp_buf_tag *env, int val);
int sigsetjmp(struct __jmp_buf_tag *env, int savemask);
__slibc_noreturn void siglongjmp(struct __jmp_buf_tag *env, int val);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_SETJMP_H */
