/* signal.h — signals.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SIGNAL_H
#define _SLIBC_SIGNAL_H

#include <sys/types.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef size_t sighandler_t;
typedef struct {
    unsigned long __val[16];
} sigset_t;
typedef struct {
    int si_signo;
    int si_errno;
    int si_code;
    int _pad[29];
} __slibc_aligned(8) siginfo_t;
struct sigaction {
    union {
        void (*sa_handler)(int);
        void (*sa_sigaction)(int, siginfo_t *, void *);
        sighandler_t __sa_word;
    };
    sigset_t sa_mask;
    int sa_flags;
    void (*sa_restorer)(void);
};
typedef struct {
    void *ss_sp;
    int ss_flags;
    size_t ss_size;
} stack_t;

#define BUS_ADRALN (1)
#define BUS_ADRERR (2)
#define BUS_OBJERR (3)
#define CLD_CONTINUED (6)
#define CLD_DUMPED (3)
#define CLD_EXITED (1)
#define CLD_KILLED (2)
#define CLD_STOPPED (5)
#define CLD_TRAPPED (4)
#define ILL_ILLOPC (1)
#define ILL_ILLOPN (2)
#define ILL_PRVOPC (5)
#define MINSIGSTKSZ (8192)
#define NSIG (32)
#define SA_NOCLDSTOP (0x00000001)
#define SA_NOCLDWAIT (0x00000002)
#define SA_NODEFER (0x40000000)
#define SA_ONSTACK (0x08000000)
#define SA_RESETHAND (((int)0x80000000))
#define SA_RESTART (0x10000000)
#define SA_SIGINFO (0x00000004)
#define SEGV_ACCERR (2)
#define SEGV_MAPERR (1)
#define SIGABRT (6)
#define SIGALRM (14)
#define SIGBUS (7)
#define SIGCHLD (17)
#define SIGCONT (18)
#define SIGFPE (8)
#define SIGHUP (1)
#define SIGILL (4)
#define SIGINT (2)
#define SIGIO (29)
#define SIGIOT (6)
#define SIGKILL (9)
#define SIGPIPE (13)
#define SIGPOLL (SIGIO)
#define SIGPROF (27)
#define SIGPWR (30)
#define SIGQUIT (3)
#define SIGSEGV (11)
#define SIGSTKFLT (16)
#define SIGSTKSZ (16384)
#define SIGSTOP (19)
#define SIGSYS (31)
#define SIGTERM (15)
#define SIGTRAP (5)
#define SIGTSTP (20)
#define SIGTTIN (21)
#define SIGTTOU (22)
#define SIGUNUSED (SIGSYS)
#define SIGURG (23)
#define SIGUSR1 (10)
#define SIGUSR2 (12)
#define SIGVTALRM (26)
#define SIGWINCH (28)
#define SIGXCPU (24)
#define SIGXFSZ (25)
#define SIG_BLOCK (0)
#define SIG_DFL (0)
#define SIG_ERR (((sighandler_t)~0))
#define SIG_IGN (1)
#define SIG_SETMASK (2)
#define SIG_UNBLOCK (1)
#define SI_KERNEL (0x80)
#define SI_QUEUE (-1)
#define SI_TIMER (-2)
#define SI_USER (0)
#define SS_DISABLE (2)
#define SS_ONSTACK (1)

int kill(pid_t pid, int sig);
int killpg(pid_t pgrp, int sig);
int raise(int sig);
int sigaction(int sig, const struct sigaction *act, struct sigaction *oact);
int sigaltstack(const stack_t *ss, stack_t *oss);
int sigemptyset(sigset_t *set);
int sigfillset(sigset_t *set);
int sigaddset(sigset_t *set, int sig);
int sigdelset(sigset_t *set, int sig);
int sigismember(const sigset_t *set, int sig);
int sigprocmask(int how, const sigset_t *set, sigset_t *oset);
int sigpending(sigset_t *set);
int sigsuspend(const sigset_t *set);
sighandler_t signal(int signum, sighandler_t handler);
char *strsignal(int sig);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_SIGNAL_H */
