/* stdio.h — buffered input/output.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_STDIO_H
#define _SLIBC_STDIO_H

#include <sys/types.h>
#include <unistd.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _slibc_file FILE;
typedef __builtin_va_list va_list;

#define EOF (-1)
#define _IOFBF (0)
#define _IOLBF (1)
#define _IONBF (2)
#define BUFSIZ (4096)

extern FILE *stdin;
extern FILE *stdout;
extern FILE *stderr;

int remove(const char *path);
int rename(const char *oldpath, const char *newpath);
int renameat(int olddirfd, const char *oldpath, int newdirfd, const char *newpath);
void clearerr(FILE *stream);
int fclose(FILE *stream);
FILE *fdopen(int fd, const char *mode);
int feof(FILE *stream);
int ferror(FILE *stream);
int fflush(FILE *stream);
int fgetc(FILE *stream);
int fgetc_unlocked(FILE *stream);
char *fgets(char *s, int n, FILE *stream);
char *fgets_unlocked(char *s, int n, FILE *stream);
int fileno(FILE *stream);
void flockfile(FILE *stream);
FILE *fopen(const char *path, const char *mode);
int fprintf(FILE *stream, const char *fmt, ...);
int fputc(int c, FILE *stream);
int fputc_unlocked(int c, FILE *stream);
int fputs(const char *s, FILE *stream);
int fputs_unlocked(const char *s, FILE *stream);
size_t fread(void *ptr, size_t size, size_t nmemb, FILE *stream);
size_t fread_unlocked(void *ptr, size_t size, size_t nmemb, FILE *stream);
int fscanf(FILE *stream, const char *fmt, ...);
int fseek(FILE *stream, long offset, int whence);
int fseeko(FILE *stream, off_t offset, int whence);
long ftell(FILE *stream);
off_t ftello(FILE *stream);
int ftrylockfile(FILE *stream);
void funlockfile(FILE *stream);
size_t fwrite(const void *ptr, size_t size, size_t nmemb, FILE *stream);
size_t fwrite_unlocked(const void *ptr, size_t size, size_t nmemb, FILE *stream);
int getc(FILE *stream);
int getc_unlocked(FILE *stream);
int getchar(void);
int getchar_unlocked(void);
int printf(const char *fmt, ...);
int putc(int c, FILE *stream);
int putc_unlocked(int c, FILE *stream);
int putchar(int c);
int putchar_unlocked(int c);
int puts(const char *s);
void rewind(FILE *stream);
int scanf(const char *fmt, ...);
int setvbuf(FILE *stream, char *buf, int mode, size_t size);
int snprintf(char *buf, size_t n, const char *fmt, ...);
int sprintf(char *buf, const char *fmt, ...);
int sscanf(const char *buf, const char *fmt, ...);
int ungetc(int c, FILE *stream);
int ungetc_unlocked(int c, FILE *stream);
int vfprintf(FILE *stream, const char *fmt, va_list ap);
int vprintf(const char *fmt, va_list ap);
int vsnprintf(char *buf, size_t n, const char *fmt, va_list ap);
int vsprintf(char *buf, const char *fmt, va_list ap);
int vfscanf(FILE *stream, const char *fmt, va_list ap);
int vscanf(const char *fmt, va_list ap);
int vsscanf(const char *buf, const char *fmt, va_list ap);
int asprintf(char **strp, const char *fmt, ...);
int vasprintf(char **strp, const char *fmt, va_list ap);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_STDIO_H */
