/* stdlib.h — general utilities: allocation, environment, conversion.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_STDLIB_H
#define _SLIBC_STDLIB_H

#include <sys/types.h>

#define EXIT_FAILURE (1)
#define EXIT_SUCCESS (0)

void *malloc(size_t size);
void *calloc(size_t nobj, size_t size);
void *realloc(void *ptr, size_t size);
void free(void *ptr);
int posix_memalign(void **memptr, size_t align, size_t size);
void *memalign(size_t align, size_t size);
__slibc_noreturn void abort(void);
__slibc_noreturn void exit(int status);
int atexit(void (*cb)(void));
char *getenv(const char *name);
int setenv(const char *name, const char *val, int overwrite);
int unsetenv(const char *name);
char *realpath(const char *path, char *resolved);
int atoi(const char *s);
long atol(const char *s);
long strtol(const char *s, char **endptr, int base);
unsigned long strtoul(const char *s, char **endptr, int base);
int putenv(char *string);
size_t malloc_usable_size(void *ptr);

#endif /* _SLIBC_STDLIB_H */
