/* stdlib.h — general utilities: allocation, environment, conversion.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_STDLIB_H
#define _SLIBC_STDLIB_H

#include <sys/types.h>
#include <limits.h>

#define MB_CUR_MAX ((size_t)MB_LEN_MAX)

#ifdef __cplusplus
extern "C"
#endif
long double strtold(const char *s, char **endptr);

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    int quot;
    int rem;
} div_t;
typedef struct {
    long quot;
    long rem;
} ldiv_t;
typedef struct {
    long long quot;
    long long rem;
} lldiv_t;

#define EXIT_FAILURE (1)
#define EXIT_SUCCESS (0)

void *malloc(size_t size);
void *calloc(size_t nobj, size_t size);
void *realloc(void *ptr, size_t size);
void free(void *ptr);
int posix_memalign(void **memptr, size_t align, size_t size);
void *memalign(size_t align, size_t size);
void *aligned_alloc(size_t align, size_t size);
__slibc_noreturn void abort(void);
__slibc_noreturn void exit(int status);
int atexit(void (*cb)(void));
char *getenv(const char *name);
int setenv(const char *name, const char *val, int overwrite);
int unsetenv(const char *name);
char *realpath(const char *path, char *resolved);
int abs(int n);
long labs(long n);
long long llabs(long long n);
div_t div(int numer, int denom);
ldiv_t ldiv(long numer, long denom);
lldiv_t lldiv(long long numer, long long denom);
double atof(const char *s);
double strtod(const char *s, char **endptr);
float strtof(const char *s, char **endptr);
long long strtoll(const char *s, char **endptr, int base);
unsigned long long strtoull(const char *s, char **endptr, int base);
int __cxa_atexit(void (*dtor)(void *), void *arg, void *dso);
void __cxa_finalize(void *dso);
int __cxa_thread_atexit_impl(void (*dtor)(void *), void *arg, void *dso);
int atoi(const char *s);
long atol(const char *s);
long strtol(const char *s, char **endptr, int base);
unsigned long strtoul(const char *s, char **endptr, int base);
int putenv(char *string);
size_t malloc_usable_size(void *ptr);
int mblen(const char *s, size_t n);
int mbtowc(wchar_t *pwc, const char *s, size_t n);
int wctomb(char *s, wchar_t wc);
size_t mbstowcs(wchar_t *dst, const char *src, size_t len);
size_t wcstombs(char *dst, const wchar_t *src, size_t len);
void qsort(void *base, size_t nmemb, size_t size, int (*compar)(const void *, const void *));
void *bsearch(const void *key, const void *base, size_t nmemb, size_t size, int (*compar)(const void *, const void *));

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_STDLIB_H */
