/* strings.h — case-insensitive string comparison.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_STRINGS_H
#define _SLIBC_STRINGS_H

#include <sys/types.h>
#include <locale.h>

#ifdef __cplusplus
extern "C" {
#endif

int ffs(int i);
int strcasecmp_l(const char *s1, const char *s2, locale_t loc);
int strncasecmp_l(const char *s1, const char *s2, size_t n, locale_t loc);
int strcasecmp(const char *a, const char *b);
int strncasecmp(const char *a, const char *b, size_t n);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_STRINGS_H */
