/* string.h — string and byte operations.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_STRING_H
#define _SLIBC_STRING_H

#include <sys/types.h>
#include <locale.h>

#ifdef __cplusplus
extern "C" {
#endif

int strerror_r(int n, char *buf, size_t buflen);
void *memchr(const void *s, int c, size_t n);
int memcmp(const void *a, const void *b, size_t n);
void *memcpy(void *dest, const void *src, size_t n);
void *memmove(void *dest, const void *src, size_t n);
void *memset(void *dest, int c, size_t n);
char *strcat(char *dest, const char *src);
char *strchr(const char *s, int c);
int strcmp(const char *a, const char *b);
char *strcpy(char *dest, const char *src);
char *strerror(int n);
size_t strlen(const char *s);
char *strncat(char *dest, const char *src, size_t n);
int strncmp(const char *a, const char *b, size_t n);
char *strncpy(char *dest, const char *src, size_t n);
size_t strnlen(const char *s, size_t maxlen);
char *strrchr(const char *s, int c);
size_t strspn(const char *s, const char *accept);
size_t strcspn(const char *s, const char *reject);
char *strstr(const char *haystack, const char *needle);
int strcoll(const char *a, const char *b);
size_t strxfrm(char *dst, const char *src, size_t n);
int strcoll_l(const char *a, const char *b, locale_t loc);
size_t strxfrm_l(char *dst, const char *src, size_t n, locale_t loc);
char *strdup(const char *s);
char *strndup(const char *s, size_t n);
char *strsignal(int sig);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_STRING_H */
