/* syslog.h — system error logging.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_SYSLOG_H
#define _SLIBC_SYSLOG_H

#include <sys/types.h>
#include <stdio.h>

#define LOG_MASK(pri) (1 << (pri))
#define LOG_UPTO(pri) ((1 << ((pri) + 1)) - 1)

#ifdef __cplusplus
extern "C" {
#endif

#define LOG_EMERG (0)
#define LOG_ALERT (1)
#define LOG_CRIT (2)
#define LOG_ERR (3)
#define LOG_WARNING (4)
#define LOG_NOTICE (5)
#define LOG_INFO (6)
#define LOG_DEBUG (7)
#define LOG_KERN (0)
#define LOG_USER (8)
#define LOG_MAIL (16)
#define LOG_DAEMON (24)
#define LOG_AUTH (32)
#define LOG_SYSLOG (40)
#define LOG_LPR (48)
#define LOG_NEWS (56)
#define LOG_UUCP (64)
#define LOG_CRON (72)
#define LOG_AUTHPRIV (80)
#define LOG_FTP (88)
#define LOG_LOCAL0 (128)
#define LOG_LOCAL1 (136)
#define LOG_LOCAL2 (144)
#define LOG_LOCAL3 (152)
#define LOG_LOCAL4 (160)
#define LOG_LOCAL5 (168)
#define LOG_LOCAL6 (176)
#define LOG_LOCAL7 (184)
#define LOG_PID (0x01)
#define LOG_CONS (0x02)
#define LOG_ODELAY (0x04)
#define LOG_NDELAY (0x08)
#define LOG_NOWAIT (0x10)
#define LOG_PERROR (0x20)

void openlog(const char *ident, int option, int facility);
void closelog(void);
int setlogmask(int mask);
void syslog(int priority, const char *format, ...);
void vsyslog(int priority, const char *format, va_list ap);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_SYSLOG_H */
