/* termios.h — terminal attributes.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_TERMIOS_H
#define _SLIBC_TERMIOS_H

#include <sys/types.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef unsigned char cc_t;
typedef unsigned int speed_t;
typedef unsigned int tcflag_t;
struct termios {
    tcflag_t c_iflag;
    tcflag_t c_oflag;
    tcflag_t c_cflag;
    tcflag_t c_lflag;
    cc_t c_line;
    cc_t c_cc[19];
    speed_t c_ispeed;
    speed_t c_ospeed;
};

#define BRKINT (0000002)
#define CLOCAL (0004000)
#define CREAD (0000200)
#define CS8 (0000060)
#define ECHO (0000010)
#define ECHOE (0000020)
#define ECHOK (0000040)
#define ECHONL (0000100)
#define ICANON (0000002)
#define ICRNL (0000400)
#define IEXTEN (0100000)
#define IGNBRK (0000001)
#define IGNCR (0000200)
#define IGNPAR (0000004)
#define INLCR (0000100)
#define ISIG (0000001)
#define IXOFF (0010000)
#define IXON (0002000)
#define NCCS (19)
#define NOFLSH (0000200)
#define ONLCR (0000004)
#define OPOST (0000001)
#define TCSADRAIN (1)
#define TCSAFLUSH (2)
#define TCSANOW (0)
#define TOSTOP (0000400)
#define VEOF (4)
#define VEOL (11)
#define VERASE (2)
#define VINTR (0)
#define VKILL (3)
#define VMIN (6)
#define VQUIT (1)
#define VSTART (8)
#define VSTOP (9)
#define VSUSP (10)
#define VTIME (5)

int tcgetattr(int fd, struct termios *termios_p);
int tcsetattr(int fd, int optional_actions, const struct termios *termios_p);
speed_t cfgetispeed(const struct termios *termios_p);
speed_t cfgetospeed(const struct termios *termios_p);
int cfsetispeed(struct termios *termios_p, speed_t speed);
int cfsetospeed(struct termios *termios_p, speed_t speed);
void cfmakeraw(struct termios *termios_p);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_TERMIOS_H */
