/* time.h — time and clocks.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_TIME_H
#define _SLIBC_TIME_H

#include <sys/types.h>

struct timespec {
    time_t tv_sec;
    long tv_nsec;
};
struct tm {
    int tm_sec;
    int tm_min;
    int tm_hour;
    int tm_mday;
    int tm_mon;
    int tm_year;
    int tm_wday;
    int tm_yday;
    int tm_isdst;
    long tm_gmtoff;
    const char *tm_zone;
};

#define CLOCK_BOOTTIME (7)
#define CLOCK_MONOTONIC (1)
#define CLOCK_MONOTONIC_COARSE (6)
#define CLOCK_MONOTONIC_RAW (4)
#define CLOCK_PROCESS_CPUTIME_ID (2)
#define CLOCK_REALTIME (0)
#define CLOCK_REALTIME_COARSE (5)
#define CLOCK_THREAD_CPUTIME_ID (3)
#define TIMER_ABSTIME (1)

int clock_gettime(clockid_t clk_id, struct timespec *tp);
int clock_settime(clockid_t clk_id, const struct timespec *tp);
int clock_getres(clockid_t clk_id, struct timespec *tp);
int clock_nanosleep(clockid_t clk_id, int flags, const struct timespec *rqtp, struct timespec *rmtp);
int nanosleep(const struct timespec *rqtp, struct timespec *rmtp);
time_t time(time_t *tloc);

#endif /* _SLIBC_TIME_H */
