/* unistd.h — core POSIX API: descriptors, paths, identity, processes.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_UNISTD_H
#define _SLIBC_UNISTD_H

#include <sys/types.h>

#define _POSIX_VERSION 200809L
#define _POSIX_THREADS 200809L
#define _POSIX_TIMERS 200809L
#define _POSIX_MONOTONIC_CLOCK 200809L
#define _POSIX_MAPPED_FILES 200809L
#define _POSIX_MEMORY_PROTECTION 200809L
#define _POSIX_THREAD_SAFE_FUNCTIONS 200809L

#ifdef __cplusplus
extern "C" {
#endif

#define STDIN_FILENO (0)
#define STDOUT_FILENO (1)
#define STDERR_FILENO (2)
#define _SC_ARG_MAX (0)
#define _PC_NAME_MAX (3)
#define _PC_PATH_MAX (4)
#define F_OK (0)
#define R_OK (4)
#define SEEK_CUR (1)
#define SEEK_END (2)
#define SEEK_SET (0)
#define W_OK (2)
#define X_OK (1)
#define _SC_CLK_TCK (2)
#define _SC_GETPW_R_SIZE_MAX (70)
#define _SC_HOST_NAME_MAX (180)
#define _SC_IOV_MAX (60)
#define _SC_NPROCESSORS_CONF (83)
#define _SC_NPROCESSORS_ONLN (84)
#define _SC_OPEN_MAX (4)
#define _SC_PAGESIZE (30)
#define _SC_PAGE_SIZE (_SC_PAGESIZE)
#define _SC_SYMLOOP_MAX (173)
#define _SC_THREAD_STACK_MIN (75)

extern char **environ;

int close(int fd);
ssize_t read(int fd, void *buf, size_t count);
ssize_t write(int fd, const void *buf, size_t count);
ssize_t pread(int fd, void *buf, size_t count, off_t offset);
ssize_t pwrite(int fd, const void *buf, size_t count, off_t offset);
off_t lseek(int fd, off_t offset, int whence);
int fsync(int fd);
int fdatasync(int fd);
void sync(void);
int ftruncate(int fd, off_t length);
int truncate(const char *path, off_t length);
int dup(int fd);
int dup2(int src, int dst);
int dup3(int src, int dst, int flags);
int pipe(int *fds);
int pipe2(int *fds, int flags);
int isatty(int fd);
int ttyname_r(int fd, char *buf, size_t buflen);
int access(const char *path, int mode);
int faccessat(int dirfd, const char *path, int mode, int flags);
int chown(const char *path, uid_t uid, gid_t gid);
int lchown(const char *path, uid_t uid, gid_t gid);
int fchown(int fd, uid_t uid, gid_t gid);
int fchownat(int dirfd, const char *path, uid_t uid, gid_t gid, int flags);
char *getcwd(char *buf, size_t size);
int chdir(const char *path);
int fchdir(int fd);
int chroot(const char *path);
int rmdir(const char *path);
int unlink(const char *path);
int unlinkat(int dirfd, const char *path, int flags);
int link(const char *src, const char *dst);
int linkat(int srcdirfd, const char *src, int dstdirfd, const char *dst, int flags);
int symlink(const char *target, const char *linkpath);
int symlinkat(const char *target, int dirfd, const char *linkpath);
ssize_t readlink(const char *path, char *buf, size_t bufsiz);
ssize_t readlinkat(int dirfd, const char *path, char *buf, size_t bufsiz);
int brk(void *addr);
void *sbrk(long increment);
pid_t getpid(void);
pid_t getppid(void);
pid_t gettid(void);
uid_t getuid(void);
uid_t geteuid(void);
gid_t getgid(void);
gid_t getegid(void);
int setuid(uid_t uid);
int seteuid(uid_t uid);
int setgid(gid_t gid);
int setegid(gid_t gid);
int setgroups(size_t ngroups, const gid_t *ptr);
int getgroups(int ngroups, gid_t *ptr);
pid_t setsid(void);
int setpgid(pid_t pid, pid_t pgid);
pid_t getpgid(pid_t pid);
pid_t getpgrp(void);
pid_t fork(void);
int execv(const char *path, const char *const *argv);
int execve(const char *path, const char *const *argv, const char *const *envp);
int execvp(const char *file, const char *const *argv);
__slibc_noreturn void _exit(int status);
unsigned int alarm(unsigned int seconds);
int gethostname(char *name, size_t len);
long sysconf(int name);
long syscall(long num, ...);
unsigned int sleep(unsigned int seconds);
int usleep(useconds_t usec);
pid_t getsid(pid_t pid);
long pathconf(const char *path, int name);
long fpathconf(int fd, int name);
int getentropy(void *buf, size_t len);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_UNISTD_H */
