/* wchar.h — wide characters.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_WCHAR_H
#define _SLIBC_WCHAR_H

#include <sys/types.h>
#include <uchar.h>
#include <locale.h>
#include <stdio.h>

#undef WCHAR_MAX
#define WCHAR_MAX 0x7fffffff
#undef WCHAR_MIN
#define WCHAR_MIN (-WCHAR_MAX - 1)

#ifdef __cplusplus
extern "C"
#endif
long double wcstold(const wchar_t *s, wchar_t **endptr);

#ifdef __cplusplus
extern "C"
#endif
long double wcstold_l(const wchar_t *s, wchar_t **endptr, locale_t loc);

struct tm;

#ifdef __cplusplus
extern "C" {
#endif

typedef unsigned int wint_t;

#define WEOF (0xffffffff)

size_t wcslen(const wchar_t *s);
size_t wcsnlen(const wchar_t *s, size_t maxlen);
wchar_t *wmemcpy(wchar_t *dst, const wchar_t *src, size_t n);
wchar_t *wmemmove(wchar_t *dst, const wchar_t *src, size_t n);
wchar_t *wmemset(wchar_t *dst, wchar_t c, size_t n);
int wmemcmp(const wchar_t *a, const wchar_t *b, size_t n);
wchar_t *wmemchr(const wchar_t *s, wchar_t c, size_t n);
wchar_t *wcscpy(wchar_t *dst, const wchar_t *src);
wchar_t *wcsncpy(wchar_t *dst, const wchar_t *src, size_t n);
wchar_t *wcscat(wchar_t *dst, const wchar_t *src);
wchar_t *wcsncat(wchar_t *dst, const wchar_t *src, size_t n);
int wcscmp(const wchar_t *a, const wchar_t *b);
int wcsncmp(const wchar_t *a, const wchar_t *b, size_t n);
wchar_t *wcschr(const wchar_t *s, wchar_t c);
wchar_t *wcsrchr(const wchar_t *s, wchar_t c);
wchar_t *wcsstr(const wchar_t *haystack, const wchar_t *needle);
size_t wcsspn(const wchar_t *s, const wchar_t *accept);
size_t wcscspn(const wchar_t *s, const wchar_t *reject);
wchar_t *wcspbrk(const wchar_t *s, const wchar_t *accept);
wchar_t *wcstok(wchar_t *s, const wchar_t *delim, wchar_t **save);
int wcscoll(const wchar_t *a, const wchar_t *b);
size_t wcsxfrm(wchar_t *dst, const wchar_t *src, size_t n);
wchar_t *wcsdup(const wchar_t *s);
size_t mbrtowc(wchar_t *pwc, const char *s, size_t n, mbstate_t *ps);
size_t wcrtomb(char *s, wchar_t wc, mbstate_t *ps);
size_t mbrlen(const char *s, size_t n, mbstate_t *ps);
size_t mbsrtowcs(wchar_t *dst, const char **src, size_t len, mbstate_t *ps);
size_t wcsrtombs(char *dst, const wchar_t **src, size_t len, mbstate_t *ps);
size_t mbsnrtowcs(wchar_t *dst, const char **src, size_t nmc, size_t len, mbstate_t *ps);
size_t wcsnrtombs(char *dst, const wchar_t **src, size_t nwc, size_t len, mbstate_t *ps);
int mbsinit(const mbstate_t *ps);
wint_t btowc(int c);
int wctob(wint_t c);
long wcstol(const wchar_t *s, wchar_t **endptr, int base);
unsigned long wcstoul(const wchar_t *s, wchar_t **endptr, int base);
long long wcstoll(const wchar_t *s, wchar_t **endptr, int base);
unsigned long long wcstoull(const wchar_t *s, wchar_t **endptr, int base);
double wcstod(const wchar_t *s, wchar_t **endptr);
float wcstof(const wchar_t *s, wchar_t **endptr);
int wcscoll_l(const wchar_t *a, const wchar_t *b, locale_t loc);
size_t wcsxfrm_l(wchar_t *dst, const wchar_t *src, size_t n, locale_t loc);
long wcstol_l(const wchar_t *s, wchar_t **endptr, int base, locale_t loc);
unsigned long wcstoul_l(const wchar_t *s, wchar_t **endptr, int base, locale_t loc);
long long wcstoll_l(const wchar_t *s, wchar_t **endptr, int base, locale_t loc);
unsigned long long wcstoull_l(const wchar_t *s, wchar_t **endptr, int base, locale_t loc);
double wcstod_l(const wchar_t *s, wchar_t **endptr, locale_t loc);
float wcstof_l(const wchar_t *s, wchar_t **endptr, locale_t loc);
wint_t fgetwc(FILE *stream);
wint_t getwc(FILE *stream);
wint_t getwchar(void);
wint_t fputwc(wchar_t wc, FILE *stream);
wint_t putwc(wchar_t wc, FILE *stream);
wint_t putwchar(wchar_t wc);
wint_t ungetwc(wint_t wc, FILE *stream);
wchar_t *fgetws(wchar_t *s, int n, FILE *stream);
int fputws(const wchar_t *s, FILE *stream);
int fwide(FILE *stream, int mode);
int fwprintf(FILE *stream, const wchar_t *fmt, ...);
int wprintf(const wchar_t *fmt, ...);
int swprintf(wchar_t *s, size_t n, const wchar_t *fmt, ...);
int vfwprintf(FILE *stream, const wchar_t *fmt, va_list ap);
int vwprintf(const wchar_t *fmt, va_list ap);
int vswprintf(wchar_t *s, size_t n, const wchar_t *fmt, va_list ap);

#ifdef __cplusplus
}
#endif

#endif /* _SLIBC_WCHAR_H */
