//! Generate the kernel's embedded symbol table from its own ELF.
//!
//! Usage: `kallsyms <kernel.elf> <out.rs>`
//!
//! The table is what `llvm-nm -n --defined-only --demangle` lists with type
//! `t`, `T`, `w` or `W` at a kernel address, in llvm-nm's order, without
//! LLVM's `.llvm.<hash>` promotion suffix, deduplicated
//! by address and name. `<out.rs>` is rewritten only when the table changed,
//! so a kernel build whose table is already its own is a cache hit.
//! Dependency-free, so it builds for the Linux host and the SlopOS guest alike.

mod demangle;
mod elf;

use std::env;
use std::fs;
use std::path::Path;
use std::process::ExitCode;

const KERNEL_BASE: u64 = 0xffff_8000_0000_0000;

fn main() -> ExitCode {
    let args: Vec<_> = env::args_os().collect();
    if args.len() != 3 {
        eprintln!("usage: kallsyms <kernel.elf> <out.rs>");
        return ExitCode::from(2);
    }
    let (elf, out) = (Path::new(&args[1]), Path::new(&args[2]));
    match run(elf, out) {
        Ok(()) => ExitCode::SUCCESS,
        Err(msg) => {
            eprintln!("kallsyms: {}: {msg}", elf.display());
            ExitCode::FAILURE
        }
    }
}

fn run(elf: &Path, out: &Path) -> Result<(), String> {
    let mut symbols = elf::text_symbols(elf)?;
    symbols.retain(|s| s.addr >= KERNEL_BASE && !s.name.is_empty() && !s.name.starts_with(b".L"));
    symbols.sort_unstable_by(|a, b| (a.addr, &a.name, a.size).cmp(&(b.addr, &b.name, b.size)));

    let mut table: Vec<(u64, Vec<u8>)> = Vec::with_capacity(symbols.len());
    let mut group_start = 0;
    for sym in &symbols {
        let name = demangle::demangle(without_promotion_suffix(&sym.name)).map_err(
            |demangle::Unsupported(scheme)| {
                format!(
                    "{} is a {scheme} name, which llvm-nm would demangle and this tool cannot",
                    String::from_utf8_lossy(&sym.name)
                )
            },
        )?;
        if table
            .get(group_start)
            .is_some_and(|&(addr, _)| addr != sym.addr)
        {
            group_start = table.len();
        }
        if !table[group_start..].iter().any(|(_, seen)| *seen == name) {
            table.push((sym.addr, name));
        }
    }

    let rendered = render(&table);
    if fs::read(out).is_ok_and(|current| current == rendered.as_bytes()) {
        println!(
            "kallsyms: {} symbols unchanged in {}",
            table.len(),
            out.display()
        );
        return Ok(());
    }
    fs::write(out, rendered).map_err(|e| format!("writing {}: {e}", out.display()))?;
    println!(
        "kallsyms: wrote {} symbols to {}",
        table.len(),
        out.display()
    );
    Ok(())
}

/// LLVM names a local it promotes across codegen units `<name>.llvm.<hash>`,
/// hashing the module; the table sits in one of those modules, so kept, the
/// suffix changes the table on every build and it never reaches a fixed point.
fn without_promotion_suffix(name: &[u8]) -> &[u8] {
    const SUFFIX: &[u8] = b".llvm.";
    match name.windows(SUFFIX.len()).rposition(|w| w == SUFFIX) {
        Some(at)
            if name.len() > at + SUFFIX.len()
                && name[at + SUFFIX.len()..].iter().all(u8::is_ascii_digit) =>
        {
            &name[..at]
        }
        _ => name,
    }
}

#[cfg(test)]
mod tests {
    use super::without_promotion_suffix;

    #[test]
    fn drops_only_a_numeric_promotion_suffix() {
        assert_eq!(
            without_promotion_suffix(b"_RNvC1a4main.llvm.12345"),
            b"_RNvC1a4main"
        );
        for kept in [
            &b"_RNvC1a4main"[..],
            b"a.llvm.",
            b"a.llvm.12x",
            b"a.llvm.1.cold",
        ] {
            assert_eq!(without_promotion_suffix(kept), kept);
        }
    }
}

fn render(table: &[(u64, Vec<u8>)]) -> String {
    let mut s = String::with_capacity(table.len() * 96);
    s.push_str("// Generated by tools/kallsyms.\n");
    s.push_str("pub static KERNEL_SYMBOLS: &[crate::ksym::KernelSymbol] = &[\n");
    for (addr, name) in table {
        s.push_str(&format!(
            "    crate::ksym::KernelSymbol {{ addr: 0x{addr:016x}, name: \""
        ));
        for c in String::from_utf8_lossy(name).chars() {
            match c {
                '\\' => s.push_str("\\\\"),
                '"' => s.push_str("\\\""),
                '\n' => s.push_str("\\n"),
                '\r' => s.push_str("\\r"),
                '\t' => s.push_str("\\t"),
                ' '..='~' => s.push(c),
                _ => s.push_str(&format!("\\u{{{:x}}}", u32::from(c))),
            }
        }
        s.push_str("\" },\n");
    }
    s.push_str("];\n");
    s
}
