[package]
name = "slopos-drivers"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

test = false
doctest = false
[features]
default = []
test-hooks = ["slopos-core/test-hooks", "slopos-net/test-hooks"]

[dependencies]
slopos-abi = { workspace = true }
slopos-acpi = { workspace = true }
slopos-arch = { workspace = true }
slopos-core = { workspace = true }
slopos-fs = { workspace = true }
slopos-font = { workspace = true, features = ["kernel"] }
slopos-kernel-services = { workspace = true }
slopos-keymap-core = { workspace = true }
slopos-testing = { workspace = true }
slopos-mm = { workspace = true }
slopos-net = { workspace = true }
slopos-ostd = { workspace = true }
slopos-vt = { workspace = true }
bitflags = { workspace = true }
