/* netinet/in.h — internet addresses.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_NETINET_IN_H
#define _SLIBC_NETINET_IN_H

#include <sys/socket.h>

typedef unsigned int in_addr_t;
typedef unsigned short in_port_t;
struct in_addr {
    in_addr_t s_addr;
};
struct in6_addr {
    unsigned char s6_addr[16];
};
struct ip_mreq {
    struct in_addr imr_multiaddr;
    struct in_addr imr_interface;
};
struct ip_mreqn {
    struct in_addr imr_multiaddr;
    struct in_addr imr_address;
    int imr_ifindex;
};
struct sockaddr_in {
    sa_family_t sin_family;
    in_port_t sin_port;
    struct in_addr sin_addr;
    unsigned char sin_zero[8];
};
struct sockaddr_in6 {
    sa_family_t sin6_family;
    in_port_t sin6_port;
    unsigned int sin6_flowinfo;
    struct in6_addr sin6_addr;
    unsigned int sin6_scope_id;
};

#define INADDR_ANY (0)
#define INADDR_BROADCAST (0xffffffff)
#define INADDR_LOOPBACK (0x7f000001)
#define INADDR_NONE (0xffffffff)
#define IPPROTO_ICMP (1)
#define IPPROTO_IP (0)
#define IPPROTO_IPV6 (41)
#define IPPROTO_TCP (6)
#define IPPROTO_UDP (17)
#define IPV6_ADD_MEMBERSHIP (20)
#define IPV6_DROP_MEMBERSHIP (21)
#define IPV6_MULTICAST_HOPS (18)
#define IPV6_MULTICAST_IF (17)
#define IPV6_MULTICAST_LOOP (19)
#define IPV6_UNICAST_HOPS (16)
#define IPV6_V6ONLY (26)
#define IP_ADD_MEMBERSHIP (35)
#define IP_DROP_MEMBERSHIP (36)
#define IP_HDRINCL (3)
#define IP_MULTICAST_IF (32)
#define IP_MULTICAST_LOOP (34)
#define IP_MULTICAST_TTL (33)
#define IP_TOS (1)
#define IP_TTL (2)
#define TCP_KEEPCNT (6)
#define TCP_KEEPIDLE (4)
#define TCP_KEEPINTVL (5)
#define TCP_NODELAY (1)

#endif /* _SLIBC_NETINET_IN_H */
