/* netinet/in.h — internet addresses.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_NETINET_IN_H
#define _SLIBC_NETINET_IN_H

#include <sys/socket.h>

#define __SLIBC_IN6_ZERO8(a) (((a)->s6_addr[0] | (a)->s6_addr[1] | (a)->s6_addr[2] | (a)->s6_addr[3] | (a)->s6_addr[4] | (a)->s6_addr[5] | (a)->s6_addr[6] | (a)->s6_addr[7]) == 0)
#define IN6_IS_ADDR_UNSPECIFIED(a) (__SLIBC_IN6_ZERO8(a) && (((a)->s6_addr[8] | (a)->s6_addr[9] | (a)->s6_addr[10] | (a)->s6_addr[11] | (a)->s6_addr[12] | (a)->s6_addr[13] | (a)->s6_addr[14] | (a)->s6_addr[15]) == 0))
#define IN6_IS_ADDR_LOOPBACK(a) \
    (__SLIBC_IN6_ZERO8(a) && (((a)->s6_addr[8] | (a)->s6_addr[9] | (a)->s6_addr[10] | (a)->s6_addr[11] | (a)->s6_addr[12] | (a)->s6_addr[13] | (a)->s6_addr[14]) == 0) && (a)->s6_addr[15] == 1)
#define IN6_IS_ADDR_MULTICAST(a) ((a)->s6_addr[0] == 0xff)
#define IN6_IS_ADDR_LINKLOCAL(a) ((a)->s6_addr[0] == 0xfe && ((a)->s6_addr[1] & 0xc0) == 0x80)
#define IN6_IS_ADDR_SITELOCAL(a) ((a)->s6_addr[0] == 0xfe && ((a)->s6_addr[1] & 0xc0) == 0xc0)
#define IN6_IS_ADDR_V4MAPPED(a) \
    (__SLIBC_IN6_ZERO8(a) && (a)->s6_addr[8] == 0 && (a)->s6_addr[9] == 0 && \
     (a)->s6_addr[10] == 0xff && (a)->s6_addr[11] == 0xff)
#define IN6_IS_ADDR_V4COMPAT(a) \
    (__SLIBC_IN6_ZERO8(a) && (((a)->s6_addr[8] | (a)->s6_addr[9] | (a)->s6_addr[10] | (a)->s6_addr[11]) == 0) && \
     !IN6_IS_ADDR_UNSPECIFIED(a) && !IN6_IS_ADDR_LOOPBACK(a))
#define IN6_IS_ADDR_MC_NODELOCAL(a) (IN6_IS_ADDR_MULTICAST(a) && ((a)->s6_addr[1] & 0xf) == 0x1)
#define IN6_IS_ADDR_MC_LINKLOCAL(a) (IN6_IS_ADDR_MULTICAST(a) && ((a)->s6_addr[1] & 0xf) == 0x2)
#define IN6_IS_ADDR_MC_SITELOCAL(a) (IN6_IS_ADDR_MULTICAST(a) && ((a)->s6_addr[1] & 0xf) == 0x5)
#define IN6_IS_ADDR_MC_ORGLOCAL(a) (IN6_IS_ADDR_MULTICAST(a) && ((a)->s6_addr[1] & 0xf) == 0x8)
#define IN6_IS_ADDR_MC_GLOBAL(a) (IN6_IS_ADDR_MULTICAST(a) && ((a)->s6_addr[1] & 0xf) == 0xe)

typedef unsigned int in_addr_t;
typedef unsigned short in_port_t;
struct in_addr {
    in_addr_t s_addr;
};
struct in6_addr {
    unsigned char s6_addr[16];
};
struct ip_mreq {
    struct in_addr imr_multiaddr;
    struct in_addr imr_interface;
};
struct ip_mreqn {
    struct in_addr imr_multiaddr;
    struct in_addr imr_address;
    int imr_ifindex;
};
struct sockaddr_in {
    sa_family_t sin_family;
    in_port_t sin_port;
    struct in_addr sin_addr;
    unsigned char sin_zero[8];
};
struct sockaddr_in6 {
    sa_family_t sin6_family;
    in_port_t sin6_port;
    unsigned int sin6_flowinfo;
    struct in6_addr sin6_addr;
    unsigned int sin6_scope_id;
};

#define INET_ADDRSTRLEN (16)
#define INET6_ADDRSTRLEN (46)
#define INADDR_ANY (0)
#define INADDR_BROADCAST (0xffffffff)
#define INADDR_LOOPBACK (0x7f000001)
#define INADDR_NONE (0xffffffff)
#define IPPROTO_ICMP (1)
#define IPPROTO_IP (0)
#define IPPROTO_IPV6 (41)
#define IPPROTO_TCP (6)
#define IPPROTO_UDP (17)
#define IPV6_ADD_MEMBERSHIP (20)
#define IPV6_DROP_MEMBERSHIP (21)
#define IPV6_MULTICAST_HOPS (18)
#define IPV6_MULTICAST_IF (17)
#define IPV6_MULTICAST_LOOP (19)
#define IPV6_UNICAST_HOPS (16)
#define IPV6_V6ONLY (26)
#define IP_ADD_MEMBERSHIP (35)
#define IP_DROP_MEMBERSHIP (36)
#define IP_HDRINCL (3)
#define IP_MULTICAST_IF (32)
#define IP_MULTICAST_LOOP (34)
#define IP_MULTICAST_TTL (33)
#define IP_TOS (1)
#define IP_TTL (2)

#endif /* _SLIBC_NETINET_IN_H */
