/* netinet/in_systm.h — network-order integer types.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_NETINET_IN_SYSTM_H
#define _SLIBC_NETINET_IN_SYSTM_H

#include <sys/types.h>

typedef unsigned short n_short;
typedef unsigned int n_long;
typedef unsigned int n_time;

#endif /* _SLIBC_NETINET_IN_SYSTM_H */
