/* netinet/tcp.h — TCP options.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_NETINET_TCP_H
#define _SLIBC_NETINET_TCP_H

#define TCP_KEEPCNT (6)
#define TCP_KEEPIDLE (4)
#define TCP_KEEPINTVL (5)
#define TCP_NODELAY (1)

#endif /* _SLIBC_NETINET_TCP_H */
