/* arpa/inet.h — internet address manipulation.
 *
 * Generated by slibc/build.rs from toolchain/libc/0001-slopos-libc.patch; do not edit.
 * Every type, constant and prototype below is the SlopOS `libc` module's own
 * declaration, so a C consumer and Rust's `std` see one ABI.
 */
#ifndef _SLIBC_ARPA_INET_H
#define _SLIBC_ARPA_INET_H

#include <netinet/in.h>

unsigned int htonl(unsigned int hostlong);
unsigned short htons(unsigned short hostshort);
unsigned int ntohl(unsigned int netlong);
unsigned short ntohs(unsigned short netshort);
in_addr_t inet_addr(const char *cp);
char *inet_ntoa(struct in_addr addr);

#endif /* _SLIBC_ARPA_INET_H */
