#!/usr/bin/env bash
set -euo pipefail

# Hold this tree to building with no registry, from the directory
# `.cargo/vendor.toml` names and `make_vendor.sh` fills. Two halves:
#
#   pins   every registry package the workspace's Cargo.lock or the pinned
#          toolchain's library/Cargo.lock names is vendored as the package its
#          lockfile checksums; nothing vendored is unnamed, since that is a pin
#          nobody reviews; and the directory's `library.lock` is std's.
#   build  `cargo check` of the kernel and the userland, `--offline --locked`,
#          from an *empty* CARGO_HOME, where a warm registry cache cannot
#          answer for a missing crate.
#
# Host builds read the registry, so a lockfile the vendored copy no longer
# describes, or a directory missing std's own dependencies, fails nowhere else.
#
# Usage: check_offline_build.sh [--self-test | --require | --pins-only]
#
#   (none)       skipped when the vendored directory has not been materialised
#   --require    fail instead of skipping
#   --pins-only  the pins half only, which takes milliseconds
#
# Environment:
#   CARGO - cargo binary (default: cargo)

SELF="check_offline_build"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

. "$SCRIPT_DIR/lib/toolchain_pin.sh"

MODE="${1:-}"
case "$MODE" in
    ""|--require|--pins-only|--self-test) ;;
    *) echo "usage: $SELF.sh [--self-test | --require | --pins-only]" >&2; exit 2 ;;
esac

CARGO="${CARGO:-cargo}"

registry_packages() {
    awk '
        function flush() {
            if (name != "" && source ~ /^"registry\+/ && checksum != "")
                print name, version, checksum
            name = version = source = checksum = ""
        }
        /^\[\[package\]\]/ { flush(); next }
        /^name = /     { name = $3;     gsub(/"/, "", name) }
        /^version = /  { version = $3;  gsub(/"/, "", version) }
        /^source = /   { source = $3 }
        /^checksum = / { checksum = $3; gsub(/"/, "", checksum) }
        END { flush() }
    ' "$1"
}

vendored_checksum() {
    sed -n 's/.*"package"[[:space:]]*:[[:space:]]*"\([0-9a-f]\{64\}\)".*/\1/p' "$1" 2>/dev/null | head -n 1
}

# Prints one finding per line, then `checked <n>`. The last lockfile is std's.
pin_findings() {
    local vendor="$1"
    shift
    local lock name version checksum dir got checked=0 named library="${*: -1}"
    named="$(mktemp)"
    for lock in "$@"; do
        registry_packages "$lock"
    done | LC_ALL=C sort -u >"$named"
    while read -r name version checksum; do
        checked=$((checked + 1))
        dir="$vendor/$name-$version"
        if [ ! -f "$dir/.cargo-checksum.json" ]; then
            echo "missing $name $version"
            continue
        fi
        got="$(vendored_checksum "$dir/.cargo-checksum.json")"
        if [ "$got" != "$checksum" ]; then
            echo "mismatch $name $version locked=$checksum vendored=${got:-none}"
        fi
    done <"$named"
    for dir in "$vendor"/*/; do
        [ -d "$dir" ] || continue
        name="$(basename "$dir")"
        awk -v want="$name" '($1 "-" $2) == want { found = 1 } END { exit !found }' "$named" ||
            echo "unpinned $name"
    done
    cmp -s "$library" "$vendor/library.lock" || echo "stale library.lock"
    rm -f "$named"
    echo "checked $checked"
}

SELF_TEST_ROOT=""

self_test() {
    local root fail=0 out
    SELF_TEST_ROOT="$(mktemp -d)"
    root="$SELF_TEST_ROOT"
    trap 'rm -rf "$SELF_TEST_ROOT"' EXIT INT TERM
    echo "$SELF: self-test against built-in fixtures"

    local sum_a sum_b sum_c
    sum_a="$(printf a | tp_sha256_stream)"
    sum_b="$(printf b | tp_sha256_stream)"
    sum_c="$(printf c | tp_sha256_stream)"
    cat >"$root/Cargo.lock" <<EOF
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "alpha"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "$sum_a"

[[package]]
name = "beta"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "$sum_b"

[[package]]
name = "local"
version = "0.1.0"
EOF
    cat >"$root/library.lock" <<EOF
version = 4

[[package]]
name = "gamma"
version = "3.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "$sum_c"
EOF
    mkdir -p "$root/vendor/alpha-1.0.0" "$root/vendor/beta-2.0.0" "$root/vendor/gamma-3.0.0"
    printf '{"files":{},"package":"%s"}' "$sum_a" >"$root/vendor/alpha-1.0.0/.cargo-checksum.json"
    printf '{"files":{},"package":"%s"}' "$sum_b" >"$root/vendor/beta-2.0.0/.cargo-checksum.json"
    printf '{"files":{},"package":"%s"}' "$sum_c" >"$root/vendor/gamma-3.0.0/.cargo-checksum.json"
    cp "$root/library.lock" "$root/vendor/library.lock"

    expect() {
        local label="$1" want="$2"
        out="$(pin_findings "$root/vendor" "$root/Cargo.lock" "$root/library.lock" | grep -v '^checked ' || true)"
        if [ "$out" = "$want" ]; then
            echo "  ok: $label"
        else
            echo "  FAIL: $label" >&2
            echo "    want: ${want:-<nothing>}" >&2
            echo "    got:  ${out:-<nothing>}" >&2
            fail=1
        fi
    }

    expect "both lockfiles satisfied, a path package ignored" ""

    printf '{"files":{},"package":"%s"}' "$sum_a" >"$root/vendor/beta-2.0.0/.cargo-checksum.json"
    expect "a vendored copy that is not the locked package" \
        "mismatch beta 2.0.0 locked=$sum_b vendored=$sum_a"
    printf '{"files":{},"package":"%s"}' "$sum_b" >"$root/vendor/beta-2.0.0/.cargo-checksum.json"

    rm -rf "$root/vendor/gamma-3.0.0"
    expect "a crate only build-std's lockfile names" "missing gamma 3.0.0"
    mkdir -p "$root/vendor/gamma-3.0.0"
    printf '{"files":{},"package":"%s"}' "$sum_c" >"$root/vendor/gamma-3.0.0/.cargo-checksum.json"

    mkdir -p "$root/vendor/stale-0.9.0"
    printf '{"files":{},"package":"%s"}' "$sum_a" >"$root/vendor/stale-0.9.0/.cargo-checksum.json"
    expect "a package no lockfile names" "unpinned stale-0.9.0"
    rm -rf "$root/vendor/stale-0.9.0"

    echo "# another nightly" >>"$root/vendor/library.lock"
    expect "a library.lock that is not std's" "stale library.lock"
    cp "$root/library.lock" "$root/vendor/library.lock"

    rm -f "$root/vendor/alpha-1.0.0/.cargo-checksum.json"
    expect "a directory with no checksum file" "missing alpha 1.0.0"

    if [ "$fail" -ne 0 ]; then
        echo "$SELF: self-test FAILED" >&2
        exit 1
    fi
    echo "$SELF: self-test OK"
}

if [ "$MODE" = "--self-test" ]; then
    self_test
    exit 0
fi

skip_or_die() {
    if [ "$MODE" = "--require" ]; then
        echo "$SELF: $*" >&2
        exit 1
    fi
    echo "$SELF: skipped — $*"
    exit 0
}

VENDOR_REL="$(tp_vendor_rel "$REPO_ROOT")" || {
    echo "$SELF: .cargo/vendor.toml names no vendored-sources directory" >&2
    exit 1
}
VENDOR="$REPO_ROOT/$VENDOR_REL"
LOCK="$REPO_ROOT/Cargo.lock"
[ -f "$LOCK" ] || { echo "$SELF: Cargo.lock is missing — it is tracked" >&2; exit 1; }
[ -d "$VENDOR" ] || skip_or_die "$VENDOR_REL is not materialised (scripts/make_vendor.sh)"

CHANNEL="$(tp_channel "$REPO_ROOT")"
SYSROOT="$(rustc +"$CHANNEL" --print sysroot 2>/dev/null)" ||
    skip_or_die "no $CHANNEL toolchain (scripts/ensure_toolchain.sh)"
LIBRARY_LOCK="$SYSROOT/$TP_LIBRARY_REL/Cargo.lock"
[ -f "$LIBRARY_LOCK" ] || skip_or_die "$LIBRARY_LOCK is missing (the rust-src component)"

# The userland's std resolves against the owned sysroot's lockfile, the
# kernel's against the toolchain's.
OWNED_LOCK="$REPO_ROOT/$TP_SYSROOT_REL/$TP_LIBRARY_REL/Cargo.lock"
if [ -f "$OWNED_LOCK" ] && ! cmp -s "$OWNED_LOCK" "$LIBRARY_LOCK"; then
    echo "$SELF: FAIL — $TP_SYSROOT_REL's std lockfile is not $CHANNEL's; one vendored directory cannot pin both" >&2
    exit 1
fi

findings="$(pin_findings "$VENDOR" "$LOCK" "$LIBRARY_LOCK")"
checked="$(printf '%s\n' "$findings" | sed -n 's/^checked //p')"
findings="$(printf '%s\n' "$findings" | grep -v '^checked ' || true)"
if [ -n "$findings" ]; then
    printf '%s\n' "$findings" | sed "s/^/$SELF: /" >&2
    echo "$SELF: FAIL — $VENDOR_REL does not describe the lockfiles; rebuild it: rm -rf $VENDOR_REL && scripts/make_vendor.sh" >&2
    exit 1
fi
[ "$checked" -gt 0 ] || { echo "$SELF: no registry packages found in either lockfile — the parse is broken" >&2; exit 1; }
echo "$SELF: pins OK — $checked registry packages across Cargo.lock and library/Cargo.lock, each the package its lockfile checksums"

[ "$MODE" = "--pins-only" ] && exit 0

[ -d "$REPO_ROOT/$TP_SYSROOT_REL" ] ||
    skip_or_die "the owned sysroot is not materialised (scripts/make_slopos_sysroot.sh), so the userland cannot be checked"

HOME_DIR="$(mktemp -d)"
trap 'rm -rf "$HOME_DIR"' EXIT INT TERM
TARGET_DIR="$REPO_ROOT/builddir/gates/offline-build"
CONFIG="$REPO_ROOT/.cargo/vendor.toml"

offline_check() {
    local toolchain="$1"
    shift
    (cd "$REPO_ROOT" &&
        env -u RUSTFLAGS -u CARGO_BUILD_RUSTFLAGS \
            CARGO_HOME="$HOME_DIR" CARGO_TARGET_DIR="$TARGET_DIR" \
            "$CARGO" +"$toolchain" check --locked --offline --quiet \
            --config "$CONFIG" -Zunstable-options "$@")
}

offline_check "$CHANNEL" \
    -Zbuild-std=core,alloc -Zbuild-std-features=compiler-builtins-mem \
    --target targets/x86_64-slos.json --package kernel --bin kernel ||
    { echo "$SELF: FAIL — the kernel does not build from $VENDOR_REL alone" >&2; exit 1; }

offline_check "$TP_TOOLCHAIN_NAME" -Zjson-target-spec \
    -Zbuild-std=core,alloc,std,panic_abort -Zbuild-std-features=compiler-builtins-mem \
    --target targets/x86_64-unknown-slopos.json --package slopos-userland --bins \
    --no-default-features --features testbins ||
    { echo "$SELF: FAIL — the userland does not build from $VENDOR_REL alone" >&2; exit 1; }

echo "$SELF: build OK — kernel and userland check from an empty CARGO_HOME, offline, against $VENDOR_REL"
