#!/usr/bin/env bash
set -euo pipefail

# The C and C++ cross compiler for `x86_64-unknown-slopos`: a target sysroot
# and the `x86_64-unknown-slopos-clang{,++}` wrappers over the host clang.
#
# Usage: make_slopos_cross.sh <sysroot> <bin dir>
#        make_slopos_cross.sh --print-stamp
#
# Callers pass their own directories: assembling a sysroot deletes it, which
# must not happen under a running `x.py`.
#
# `--print-stamp` digests this file, the host tools, slibc's headers, the C++
# runtime's stamp and ABI flags, crt0 and builtins, and the symbol *names*
# `libc.so` defines: objects built here link it, so only a new or vanished
# function changes what a probe finds. Nothing built here links `libc.a`.
#
# Needs a tests userland build in `BUILD_DIR` (default builddir) and the C++
# runtime (`scripts/make_slopos_cxx.sh`).

SELF="make_slopos_cross"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

die() {
    echo "$SELF: $1" >&2
    exit 1
}

TARGET="x86_64-unknown-slopos"
HOST_TRIPLE="x86_64-unknown-linux-gnu"
BUILD_DIR="${BUILD_DIR:-$REPO_ROOT/builddir}"
RELEASE_DIR="$BUILD_DIR/target/$TARGET/release"
CXX_DIR="$REPO_ROOT/third_party/slopos-cxx"

CXX_TOOLS="$("$SCRIPT_DIR/cxx_host_tools.sh")"
eval "$CXX_TOOLS"

for library in libc.so crt0.o libbuiltins.a; do
    [ -f "$BUILD_DIR/$library" ] ||
        die "no $library in $BUILD_DIR — run a tests userland build first"
done
[ -f "$CXX_DIR/lib/libc++.so" ] || die "no C++ runtime — run scripts/make_slopos_cxx.sh"

# Not a literal: the rune-table flag sets the layout of `ctype_base::mask`, a
# by-value type, so omitting it breaks the ABI and libc++'s `__locale`.
CXX_ABI_FLAGS="$("$SCRIPT_DIR/make_slopos_cxx.sh" --print-abi-flags)"

if [ "${1:-}" = "--print-stamp" ]; then
    {
        sha256sum "$SCRIPT_DIR/$SELF.sh" | cut -d' ' -f1
        printf '%s\n' "$CXX_TOOLS" "$CXX_ABI_FLAGS"
        "$CLANG" --version | head -n 1
        (cd "$REPO_ROOT/slibc/include" && find . -type f -print | LC_ALL=C sort | xargs sha256sum)
        cat "$CXX_DIR/.slopos-stamp" 2>/dev/null || echo "no C++ runtime stamp"
        sha256sum "$BUILD_DIR/crt0.o" "$BUILD_DIR/libbuiltins.a" | cut -d' ' -f1
        readelf --dyn-syms -W "$BUILD_DIR/libc.so" |
            awk 'NF >= 8 && $1 ~ /:$/ && $7 != "UND" { print $8 }' | LC_ALL=C sort -u
    } | sha256sum | cut -d' ' -f1
    exit 0
fi

[ $# -eq 2 ] || die "usage: $SELF.sh <sysroot> <bin dir> | --print-stamp"
[ -f "$RELEASE_DIR/libc.a" ] || die "no libc.a in $RELEASE_DIR — run a tests userland build first"
SYSROOT="$1"
WRAPPER_DIR="$2"
case "$SYSROOT$WRAPPER_DIR" in
    *[[:space:]]*) die "the wrapper cannot take a path containing whitespace: $SYSROOT $WRAPPER_DIR" ;;
esac

# Copied with their times, or ninja recompiles the whole cross LLVM, which
# depends on these headers.
rm -rf "$SYSROOT"
mkdir -p "$SYSROOT/lib" "$SYSROOT/include" "$WRAPPER_DIR"
cp -p "$BUILD_DIR/libc.so" "$BUILD_DIR/crt0.o" "$BUILD_DIR/libbuiltins.a" "$SYSROOT/lib/"
cp -p "$RELEASE_DIR/libc.a" "$SYSROOT/lib/"
cp -p "$CXX_DIR/lib/libc++.so" "$CXX_DIR/lib/libc++.a" "$SYSROOT/lib/"
cp -rp "$REPO_ROOT/slibc/include/." "$SYSROOT/include/"
cp -rp "$CXX_DIR/include/c++" "$SYSROOT/include/c++"
SYSROOT="$(cd "$SYSROOT" && pwd)"

# slibc has no separate libm, libdl, libpthread or librt; empty archives, as
# musl-derived sysroots ship, stop a probe for them finding the host's.
for stub in m dl pthread rt util; do
    "$LLVM_AR" crs "$SYSROOT/lib/lib$stub.a"
done

# `toolchains::SlopOS` in shell, until a clang built from `toolchain/llvm/`
# runs the build. It compiles and links with different triples: compiling
# must name SlopOS or `__linux__` is defined, and the host clang has no SlopOS
# toolchain, so linking with that triple would hand off to host `gcc` and its
# library paths. Linking as the host triple keeps `ld.lld`, and `--sysroot`
# makes a stray `-lm` a link error. The host clang predefines nothing for an
# OS it does not know, so the wrapper defines what `SlopOSTargetInfo` does.
write_wrapper() {
    local path="$1" compiler="$2" stdlib="$3" stdlib_libs="${4:-}"
    cat >"$path" <<WRAPPER
#!/bin/sh
set -e
# Generated by scripts/$SELF.sh — do not edit.
sysroot="$SYSROOT"
cflags="--target=$TARGET -D__slopos__ -D__unix -D__unix__ -nostdlibinc $stdlib -isystem \$sysroot/include"
cflags="\$cflags -Wno-unused-command-line-argument"

# Expand response files first, or a long CMake link line (\`@file\`) is taken
# for a compile. Every other argument is kept whole: git passes
# \`-DPAGER_ENV="LESS=FRX LV=-c"\`.
remaining=\$#
while [ "\$remaining" -gt 0 ]; do
    arg="\$1"
    shift
    remaining=\$((remaining - 1))
    case "\$arg" in
        @*)
            file="\${arg#@}"
            [ -f "\$file" ] || { echo "\$0: no response file \$file" >&2; exit 1; }
            # shellcheck disable=SC2046
            set -- "\$@" \$(tr '\n' ' ' <"\$file")
            ;;
        *) set -- "\$@" "\$arg" ;;
    esac
done

# A caller's \`--target\` is dropped: the \`cc\` crate passes
# \`x86_64-unknown-slopos-slibc\`, which clang rejects as a triple.
# \`-X<tool>\` operands belong to that tool: \`-Xlinker -E\` is not \`clang -E\`.
linking=1
shared=0
static=0
static_cxx=0
gnu=1
carry=0
drop=0
remaining=\$#
while [ "\$remaining" -gt 0 ]; do
    arg="\$1"
    shift
    remaining=\$((remaining - 1))
    if [ "\$drop" -eq 1 ]; then
        drop=0
        continue
    fi
    if [ "\$carry" -eq 1 ]; then
        carry=0
        set -- "\$@" "\$arg"
        continue
    fi
    case "\$arg" in
        --target=*) continue ;;
        -target)
            drop=1
            continue
            ;;
        -Xlinker | -Xassembler | -Xpreprocessor) carry=1 ;;
        -c | -S | -E | -M | -MM | -fsyntax-only | -### | --version | --help | -dumpmachine | -dumpversion | -print-* | --print-*)
            linking=0
            ;;
        -shared) shared=1 ;;
        -static) static=1 ;;
        -pthread) cflags="\$cflags -D_REENTRANT" ;;
        -std=gnu*) gnu=1 ;;
        -std=* | -ansi) gnu=0 ;;
        -static-libstdc++) static_cxx=1 ;;
    esac
    set -- "\$@" "\$arg"
done

[ "\$gnu" -eq 0 ] || cflags="\$cflags -Dunix"

if [ "\$linking" -eq 0 ]; then
    # The host driver answers \`-print-file-name\` with the bare name for this
    # triple; bootstrap needs the sysroot path to find \`libc++.a\`.
    for arg in "\$@"; do
        case "\$arg" in
            -print-file-name=*)
                if [ -f "\$sysroot/lib/\${arg#-print-file-name=}" ]; then
                    printf '%s\n' "\$sysroot/lib/\${arg#-print-file-name=}"
                    exit 0
                fi
                ;;
        esac
    done
    exec $compiler \$cflags "\$@"
fi

# A link may carry sources (CMake's \`try_compile\`): compile them for SlopOS
# first. Other flags (\`-O2\`, \`-g\`, \`-flto\`) go to both phases.
objects=""
link_args=""
compile_args=""
output=""
sources=""
skip=0
carry=0
for arg in "\$@"; do
    if [ "\$skip" -eq 1 ]; then
        output="\$arg"
        skip=0
        continue
    fi
    if [ "\$carry" -eq 1 ]; then
        carry=0
        link_args="\$link_args \$arg"
        continue
    fi
    case "\$arg" in
        -o) skip=1 ;;
        -o*) output="\${arg#-o}" ;;
        -Xlinker)
            carry=1
            link_args="\$link_args \$arg"
            ;;
        -l* | -L* | -Wl,* | -shared | -static | -rdynamic | -pie | -no-pie)
            link_args="\$link_args \$arg"
            ;;
        -*)
            compile_args="\$compile_args \$arg"
            link_args="\$link_args \$arg"
            ;;
        *.c | *.cc | *.cpp | *.cxx | *.C | *.s | *.S) sources="\$sources \$arg" ;;
        *.o | *.a | *.so | *.so.*) link_args="\$link_args \$arg" ;;
        *)
            compile_args="\$compile_args \$arg"
            link_args="\$link_args \$arg"
            ;;
    esac
done
[ "\$skip" -eq 0 ] || { echo "\$0: -o with no operand" >&2; exit 1; }

tmp="\$(mktemp -d)"
trap 'rm -rf "\$tmp"' EXIT INT TERM
for source in \$sources; do
    obj="\$tmp/\$(printf '%s' "\$source" | tr '/.' '__').o"
    $compiler \$cflags \$compile_args -c "\$source" -o "\$obj"
    objects="\$objects \$obj"
done
[ -n "\$output" ] || output=a.out

# Objects ahead of \`-l\` and \`.a\`: archive resolution is order-sensitive.
set -- --target=$HOST_TRIPLE --sysroot="\$sysroot" --gcc-toolchain="\$sysroot" -fuse-ld=lld -nostdlib \\
    -Wno-unused-command-line-argument -L"\$sysroot/lib" \\
    \$objects \$link_args -o "\$output" -Wl,--eh-frame-hdr
if [ "\$shared" -eq 0 ]; then
    set -- -no-pie "\$@" -Wl,--image-base=0x400000 "\$sysroot/lib/crt0.o"
fi
if [ "\$static" -eq 0 ]; then
    set -- "\$@" -Wl,-z,now
    [ "\$shared" -eq 1 ] || set -- "\$@" -Wl,--dynamic-linker=/lib/ld-slopos.so.1
fi
# As clang's GNU toolchains do: only the C++ runtime is linked statically.
cxx_libs="$stdlib_libs"
if [ "\$static_cxx" -eq 1 ] && [ "\$static" -eq 0 ] && [ -n "\$cxx_libs" ]; then
    cxx_libs="-Wl,-Bstatic \$cxx_libs -Wl,-Bdynamic"
fi
set -- "\$@" \$cxx_libs -lc "\$sysroot/lib/libbuiltins.a"
status=0
$compiler "\$@" || status=\$?
rm -rf "\$tmp"
trap - EXIT INT TERM
exit "\$status"
WRAPPER
    chmod +x "$path"
}

write_wrapper "$WRAPPER_DIR/$TARGET-clang" "$CLANG" ""
write_wrapper "$WRAPPER_DIR/$TARGET-clang++" "$CLANGXX" \
    "-nostdinc++ -isystem $SYSROOT/include/c++/v1 $CXX_ABI_FLAGS" "-lc++"
